Fix of the script configure

diff --git a/bin/Installer_TRUST b/bin/Installer_TRUST
--- a/bin/Installer_TRUST
+++ b/bin/Installer_TRUST
@@ -11,7 +11,6 @@ check_prerequis()
 [ -f $TRUST_ROOT/bin/linux_install_tools_`uname -m`.tgz ] && echo "linux_install_tools.tgz exists"
 if [ "`uname -s`" = Linux ] && [ -f $TRUST_ROOT/bin/linux_install_tools_`uname -m`.tgz ]
 then
-    export PATH=$PATH:$TRUST_ROOT/bin/bin
     cd $TRUST_ROOT/bin
     mkdir -p bin 2>/dev/null
     (cd bin;tar xfz ../linux_install_tools_`uname -m`.tgz)
@@ -50,7 +49,7 @@ do
       then
         pp="lzip"
         echo "You need $pp installed before installing the provided $p. Try to install it"
-        dest2=tmp_$pp
+        dest2=$TRUST_ROOT/tmp_$pp
         q=$pp
         rm -rf $dest2
         mkdir $dest2
@@ -60,18 +59,20 @@ do
         tar zxf $TRUST_ROOT/externalpackages/utils/$arch
         cd *$q*
         ./configure --prefix=$TRUST_ROOT/exec/utils >config.log 2>&1  && make >make.log 2>&1  && make install > install.log 2>&1
-        cd ../..
+        [ $? -eq 0 ] && echo "lzip install completed"
         export PATH=$PATH:$TRUST_ROOT/exec/utils/bin
         if [ "`lzip --help 1>/dev/null 2>&1;echo $?`" != 0 ]
         then
-           echo "$pp" >> $TRUST_ROOT/NON_INSTALLED
            echo "Error while installing lzip. See informations in $dest2 directory."
+           echo "Error while installing lzip." >> $TRUST_ROOT/NON_INSTALLED
+           echo "See logfile in $dest2" >> $TRUST_ROOT/NON_INSTALLED
+           echo "---" >> $TRUST_ROOT/NON_INSTALLED
         else
           rm -rf $dest2
         fi
       fi
     fi
-    dest=tmp_$p
+    dest=$TRUST_ROOT/tmp_$p
     q=$p
     [ "$p" = "awk" ] && q=gawk
     rm -rf $dest
@@ -93,13 +94,14 @@ do
     fi
     cd *$q*
     ./configure --prefix=$TRUST_ROOT/exec/utils >config.log 2>&1  && make >make.log 2>&1  && make install > install.log 2>&1
-    [ $? -eq 0 ] && echo "install completed"
-    cd ../..
+    [ $? -eq 0 ] && echo "$p install completed"
     export PATH=$PATH:$TRUST_ROOT/exec/utils/bin
     if [ "`$p --help 1>/dev/null 2>&1;echo $?`" != 0 ]
     then
-       echo "$p" >> $TRUST_ROOT/NON_INSTALLED
        echo "Error while installing $p. See informations in $dest directory."
+       echo "Error while installing $p." >> $TRUST_ROOT/NON_INSTALLED
+       echo "See logfile in $dest/" >> $TRUST_ROOT/NON_INSTALLED
+       echo "---" >> $TRUST_ROOT/NON_INSTALLED
     else
       rm -rf $dest
     fi
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -531,24 +531,6 @@ else
 fi
 
 
-if [ "$TRUST_WITHOUT_DOC" != 1 ]
-then
-   [ "`eval pdflatex --version 1>/dev/null 2>&1;echo $?`" != 0 ] && echo "    pdflatex for doc generation" >> NON_INSTALLED
-
-   if [ "`grep 'Ubuntu ' /etc/os-release 2>/dev/null`" != "" ] || [ "`grep 'Debian ' /etc/os-release 2>/dev/null`" != "" ]
-   then
-      [ `eval dpkg-query -W texlive-fonts-recommended 1>/dev/null 2>&1;echo $?` != 0 ] && echo "    texlive-fonts-recommended for doc generation" >> NON_INSTALLED
-   elif [ "`grep 'Fedora ' /etc/os-release 2>/dev/null`" != "" ]
-   then
-      [ `eval dnf list installed texlive-fontspec 1>/dev/null 2>&1;echo $?` != 0 ] && echo "    texlive-fontspec for doc generation" >> NON_INSTALLED
-   elif [ "`grep 'CentOS ' /etc/os-release 2>/dev/null`" != "" ]
-   then
-      [ `eval yum list installed texlive-fontspec 1>/dev/null 2>&1;echo $?` != 0 ] && echo "    texlive-fontspec for doc generation" >> NON_INSTALLED
-   else
-      echo "Unknown distribution, ensure that latex and texlive-fonts-recommended are installed for doc generation."
-   fi
-fi
-
 ################################
 # Check options for some hosts #
 ################################
@@ -570,6 +552,46 @@ cd env
 
 [ "$clean" != "" ] && exit 0
 cd ..
+
+exiterror=0
+[ -f $TRUST_ROOT/NON_INSTALLED ] && exiterror=1
+
+if [ "$TRUST_WITHOUT_DOC" != 1 ]
+then
+   if [ "`eval pdfldatex --version 1>/dev/null 2>&1;echo $?`" != 0 ]
+   then
+     echo "pdflatex is missing. It is not provided with TRUST." >> NON_INSTALLED
+     echo "All TRUST documentation is available at https://sourceforge.net/projects/trust-platform/" >> NON_INSTALLED
+     echo "---" >> NON_INSTALLED
+   fi
+
+   if [ "`grep 'Ubuntu ' /etc/os-release 2>/dev/null`" != "" ] || [ "`grep 'Debian ' /etc/os-release 2>/dev/null`" != "" ]
+   then
+      [ `eval dpkg-query -W texlive-fonts-recommended 1>/dev/null 2>&1;echo $?` != 0 ] && echo "    texlive-fonts-recommended for doc generation" >> NON_INSTALLED
+   elif [ "`grep 'Fedora ' /etc/os-release 2>/dev/null`" != "" ]
+   then
+      [ `eval dnf list installed texlive-fontspec 1>/dev/null 2>&1;echo $?` != 0 ] && echo "    texlive-fontspec for doc generation" >> NON_INSTALLED
+   elif [ "`grep 'CentOS ' /etc/os-release 2>/dev/null`" != "" ]
+   then
+      [ `eval yum list installed texlive-fontspec 1>/dev/null 2>&1;echo $?` != 0 ] && echo "    texlive-fontspec for doc generation" >> NON_INSTALLED
+   else
+      echo "Unknown distribution, ensure that latex and texlive-fonts-recommended are installed for doc generation."
+   fi
+fi
+
+if [ -f $TRUST_ROOT/NON_INSTALLED ]
+then
+   echo ""
+   echo "============================================================================"
+   echo "Some packages needed by TRUST were not correctly installed:"
+   echo "----------------------------------------------------------------"
+   cat $TRUST_ROOT/NON_INSTALLED
+   [ "$multiple_choices" = 1 ] && echo "(*) Only one command is needed but none has been found!"
+   echo $ECHO_OPTS "See previous messages for further details or contact support at trust@cea.fr"
+   echo "============================================================================"
+   [ "$exiterror" = 1 ] && exit -1
+fi
+
 source ./env_TRUST.sh 1>/dev/null 2>&1
 
 ###############################################
@@ -624,18 +646,6 @@ then
    echo $ECHO_OPTS "make"
    echo $ECHO_OPTS "# To check TRUST, run:"
    echo $ECHO_OPTS "make check"
-fi
-
-if [ -f $TRUST_ROOT/NON_INSTALLED ]
-then
-   echo ""
-   echo "========================================================================="
-   echo "Some packages needed by TRUST code were not correctly installed:"
-   echo "----------------------------------------------------------------"
-   cat NON_INSTALLED
-   [ "$multiple_choices" = 1 ] && echo "(*) Only one command is needed but none has been found!"
-   echo $ECHO_OPTS "See previous messages for further details or contact support at trust@cea.fr"
-   echo "========================================================================="
 fi
 
 exit 0
