Some updates for SampleFormJupyter and trust -jupyter

diff --git a/bin/trust b/bin/trust
--- a/bin/trust
+++ b/bin/trust
@@ -458,21 +458,27 @@ do
       prm=1 
    elif [ "$1" = "-jupyter" ]
    then
-		 shift
-     if [ "$1" != "" ]
-		 then
-			 jy=$1
-		 else
-			 if [ "`basename $ici`" = src ]
-			 then
-				 jy=`cd ..;basename $PWD`
-			 else
-				 jy=`basename $PWD`
-			 fi
-		 fi
-		 tutorial=0
-		 create_basic_jupyter_notebook.sh $jy $tutorial
-		 exit $?
+      shift
+      echo "Usage:"
+      echo "You should run trust -jupyter inside a folder, ex. MyValidationForm"
+      echo " > cd MyValidationForm"
+      echo " > ls       # you should have src folder which contains at least a datafile"
+      echo " > trust -jupyter   # will create a jupyter's sample notebook"
+      [ "`ls *.ipynb 2>/dev/null`" != "" ] && echo "" && echo "Fatal error: you already have .ipynb file inside `pwd`" && exit 255
+      if [ "$1" != "" ]
+      then
+      	 jy=$1
+      else
+      	 if [ "`basename $ici`" = src ]
+      	 then
+      	    jy=`cd ..;basename $PWD`
+      	 else
+      	    jy=`basename $PWD`
+      	 fi
+      fi
+      tutorial=0
+      create_basic_jupyter_notebook.sh $jy $tutorial
+      exit $?
    elif [ "$1" = "-search" ]
    then
       shift
