[trustpy] trust -trustpy <dataset> to check a single dataset

diff --git a/bin/trust b/bin/trust
--- a/bin/trust
+++ b/bin/trust
@@ -111,6 +111,7 @@ help()
    echo "-config nedit|vim|emacs|gedit : Configure nedit or vim or emacs or gedit with TRUST keywords."
    echo "-edit                         : Edit datafile."
 #   echo "-xedit                        : Edit datafile with xdata."
+   echo "-trustpy                      : Check the datafile's keywords with trustpy."
    echo "-xcheck                       : Check the datafile's keywords with xdata."
    echo "-xdata                        : Check and run the datafile's keywords with xdata."
    echo "-partition                    : Partition the mesh to prepare a parallel calculation (Creation of the .Zones files)."
@@ -159,6 +160,7 @@ ici=`pwd`
 me=`whoami`
 edit=""
 xedit=""
+trustpy=""
 xcheck=""
 xdata=""
 partition=""
@@ -285,6 +287,9 @@ do
    elif [ "$1" = "-xedit" ]
    then
       xedit=1
+   elif [ "$1" = "-trustpy" ]
+   then
+      trustpy=1
    elif [ "$1" = "-xcheck" ]
    then
       xcheck=1
@@ -703,6 +708,17 @@ if [ "$xedit" = 1 ]
 then
    $TRUST_ROOT/bin/EditData $NOM".data"
    exit $?
+fi
+
+############################
+# Verify data with trustpy #
+############################
+if [ "$trustpy" = 1 ]
+then
+   $TRUST_ROOT/Outils/trustpy/check_single.sh $NOM".data"
+   ret=$?
+   [ $ret != 0 ] && echo "Error!"
+   exit $ret
 fi
 
 ##########################
