ARM support.

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -355,7 +355,7 @@ check_nvidia_cuda()
       echo "No NVIDIA drivers detected on $HOSTNAME."
    else
       echo "NVIDIA drivers detected on $HOSTNAME: Version $NVIDIA_VERSION"
-      BITS=32 && [ "`uname -m`" = x86_64 ] && BITS=64
+      BITS=32 && [ "`uname -m | grep 64`" != "" ] && BITS=64
       #########################################################################
       # CUDA detecte? On ne doit pas prendre CUDA d'une autre version TRUST...
       #########################################################################
@@ -767,7 +767,7 @@ case $arch in
 	#fortran_gnu="g77 gfortran" && [ "`/usr/bin/gcc --version 2>/dev/null | head -1 | awk '/ 4\./ {print 1}'`" = 1 ] && fortran_gnu="gfortran g77"
 	# 1.6.1: on place gfortran devant g77 pour profiter de MUMPS au maximum
         fortran_gnu="gfortran g77"
-	# On met icpc en 1er/GNU car sur titane (x86_64, icpc 10% plus rapide que gcc sur le cas cpu_3D...)
+	# On met icpc en 1er/GNU car sur titane (icpc 10% plus rapide que gcc sur le cas cpu_3D...)
 	# si une version recente (>=v10) d'icpc existe car sur ecrins la 8.x ne marche pas bien...
 	# 1.6.9: On interdit strictement Intel 12.x qui fait crasher/bloquer MUMPS (voir MC1520)
 	if [ "`icpc -v 2>&1 | awk 'BEGIN {ok=0} /Version/ && ($2>10) {ok=1} /version/ && (($3>10 && $3<12) || $3>=13) {ok=1} END {print ok}'`" = 1 ]
@@ -903,16 +903,21 @@ rm -f $TRUST_ROOT/exec/ccache/g??
 unset PYTHONPATH # We get a warning from Miniconda if we do not unset this variable
 
 # check the previous install of conda and conda packages if it exists
+model=`uname -m`
+system=`uname -s` && [ "$system" = Darwin ] && system=MacOSX
+pkgs="pyqt=5.6 nomkl numpy matplotlib swig=3.0.12 cmake=3.14 scipy xorg-libsm sympy"
+local_channel="-c file://$TRUST_ROOT/externalpackages/Miniconda/local_channel --override-channels"
+[ "$model" = aarch64 ] && local_channel="" && pkgs="nomkl numpy matplotlib swig=4.0.2 cmake=3.14 scipy xorg-libsm sympy"
+
 if [ -d $TRUST_ROOT/exec/python/bin ] && [ -f $TRUST_ROOT/exec/python/bin/conda ]
 then
    # check of python version
    PYTHON_VERSION_OK=`$TRUST_ROOT/exec/python/bin/python --version 2>&1 | awk '/Python/ {split($2,a,".");v=a[1]*100+a[2]*10+a[3];print (v==373?1:0)}'`
    PYTHON_TEST_OK=1 && [ "`$TRUST_ROOT/exec/python/bin/python ./test.py 1>/dev/null 2>&1;echo $?`" != 0 ] && PYTHON_TEST_OK=0
-
    INSTALL_OK=1
    # list of packages already-installed/to-install in conda
-   pkgs="pyqt nomkl numpy matplotlib swig cmake scipy xorg-libsm sympy"
-   for pkg in $pkgs ; do
+   for pkg in $pkgs; do
+     pkg=`echo $pkg | awk -F= '{print $1}'` # Pour ne pas avoir le numero de version
      [ "`$TRUST_ROOT/exec/python/bin/conda list | grep $pkg`" = "" ] && INSTALL_OK=0
    done
 
@@ -932,19 +937,17 @@ then
     [ -d $TRUST_ROOT/exec/python ] && rm -rf $TRUST_ROOT/exec/python
 
     # Then we install miniconda and the different packages
-    conda_installer=Miniconda3-4.6.14-Linux-x86_64.sh
+    conda_installer=`cd $TRUST_ROOT/externalpackages/Miniconda;ls Mini*3*-$system"-"$model.sh`
     echo "Trying to install $conda_installer"
     $TRUST_ROOT/externalpackages/Miniconda/./$conda_installer -p $TRUST_ROOT/exec/python/ -b 1>$TRUST_ROOT/exec/conda_python.log 2>&1
-    [ $? != 0 ] && echo "Error while installing $conda_installer. See $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
+    [ $? != 0 ] && echo "Error while installing $conda_installer. See $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED && exit -1
 
     # Installing packages from local channel
     cd $TRUST_ROOT/exec/python/bin
-
-    pkgs="pyqt=5.6 nomkl numpy matplotlib swig=3.0.12 cmake=3.14 scipy xorg-libsm sympy"
     for pkg in $pkgs
     do
       echo "Installing $pkg ... "
-      ./conda install -c file://$TRUST_ROOT/externalpackages/Miniconda/local_channel --override-channels $pkg -y  1>>$TRUST_ROOT/exec/conda_python.log 2>&1
+      ./conda install $local_channel $pkg -y 1>>$TRUST_ROOT/exec/conda_python.log 2>&1
       [ $? != 0 ] && echo "Error while installing '$pkg' from Miniconda3 local_channel. see $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
     done
     cd -
@@ -956,12 +959,12 @@ rm -r $TRUST_ROOT/exec/python/pkgs
 mkdir $TRUST_ROOT/exec/python/pkgs
 
 # Gestion d'une librairie systeme plus recente que miniconda (ex: libstdc++.so.26 sur Fedora30 pour libstdc++.so.25), on vire:
-stdcpp_conda=`ls $TRUST_ROOT/exec/python/lib/libstdc++.so.6.0.* 2>/dev/null`
+stdcpp_conda=`ls $TRUST_ROOT/exec/python/lib/libstdc++.so.6.0.* 2>/dev/null | cut -d'.' -f3-6`
 if [ "$stdcpp_conda" != "" ]
 then
     stdcpp_sys=`ls /usr/lib64/libstdc++.so.6.0.* 2>/dev/null | cut -d'.' -f3-6`
-    [ "$stdcpp_sys" = "" ] && stdcpp_sys=`ls /usr/lib*/x86_64-linux-gnu/libstdc++.so.6.0.* 2>/dev/null | cut -d'.' -f3-6`
-    remove_stdcpp_conda=0 && [ "$stdcpp_sys" != "" ] && remove_stdcpp_conda=`echo $stdcpp_sys | awk '{ print ($1>="6.0.25"?1:0) }'`
+    [ "$stdcpp_sys" = "" ] && stdcpp_sys=`ls /usr/lib*/*64-linux-gnu/libstdc++.so.6.0.* 2>/dev/null | cut -d'.' -f3-6`
+    remove_stdcpp_conda=0 && [ "$stdcpp_sys" != "" ] && remove_stdcpp_conda=`echo $stdcpp_sys $stdcpp_conda | awk '{ print ($1>$2?1:0) }'`
     [ $remove_stdcpp_conda -eq 1 ] && echo "we remove libstdc++.so* from conda" && rm -f $TRUST_ROOT/exec/python/lib/libstdc++.so*
 fi
 # export PATH
@@ -2260,7 +2263,7 @@ LINK_MALIB = $LINK_MALIB" > $tmp
    # On vire -fno-inline car on peut compiler fichier par fichier
    #echo $ECHO_OPTS "1,$ s?$O?-g -pg `[ $TRUST_ARCH = linux ] && echo "-fno-inline"` $O?g\nw" | ed make.$suffixe2 1>/dev/null 2>&1
    option_profile="-pg" && [ "`uname -m`" = ia64 ] && option_profile="-p" # -qp devient obsolete Intel 10
-   if [ "`uname -m`" = i686 ] || [ "`uname -m`" = x86_64 ]
+   if [ "`uname -m`" = i686 ] || [ "`uname -m | grep 64`" != "" ]
    then
       # le -gstab1 booste litteralement l'analyse par gprof avec GNU (>*10)
       # http://www.arcknowledge.com/gmane.comp.gnu.binutils.bugs/2006-04/msg00030.html
