[mpi4py] set TMPDIR, necessary if noexec /tmp

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -801,7 +801,7 @@ rm -f $TRUST_ROOT/exec/ccache/g??
 #########################################################################
 # On utilise python de conda pour PETSc, Run_fiche, MED, MEDCOUPLING, IHM
 #########################################################################
-unset PYTHONPATH # We get a warning from Miniconda if we do not unset this variable
+unset PYTHONPATH # We get a warning from conda if we do not unset this variable
 
 # check the previous install of conda and conda packages if it exists
 model=`uname -m`
@@ -841,7 +841,7 @@ then
 
           if [ `diff conda_list.ref conda_list.check 1>/dev/null 2>&1; echo $?` != 0 ]
           then
-             echo "# The current miniconda install contains some supplementary or missing packages, we clean it..."
+             echo "# The current conda install contains some supplementary or missing packages, we clean it..."
              INSTALL_OK=0
           else
              rm -f conda_list.ref
@@ -860,7 +860,7 @@ then
        then
           INSTALL_CONDA=1
        else
-          echo "# The current install of python, python packages, swig and cmake from miniconda seems OK... we skip it"
+          echo "# The current install of python, python packages, swig and cmake from conda seems OK... we skip it"
        fi
     fi
 else
@@ -892,7 +892,7 @@ then
        exit -1
     fi
 
-    # Then we install miniconda and the different packages
+    # Then we install conda and the different packages
     conda_installer=`cd $TRUST_ROOT/externalpackages/Miniconda;ls Mini*3*-$system"-"$model.sh`
     echo "Trying to install $conda_installer"
     # PL: Change le TMPDIR car par defaut sur /tmp et pb si mis a noexec
@@ -912,13 +912,13 @@ then
           echo "Installing $pkg..."
        done
        ./conda install $local_channel $pkgs -y 1>>$TRUST_ROOT/exec/conda_python.log 2>&1
-       [ $? != 0 ] && echo "Error while installing packages from Miniconda3 local_channel. See $TRUST_ROOT/exec/conda_python.log" && exit -1
+       [ $? != 0 ] && echo "Error while installing packages from conda-forge local_channel. See $TRUST_ROOT/exec/conda_python.log" && exit -1
     else
        for pkg in $pkgs
        do
          echo "Installing $pkg ... "
          time ./conda install $local_channel $pkg -y 1>>$TRUST_ROOT/exec/conda_python.log 2>&1
-         [ $? != 0 ] && echo "Error while installing '$pkg' from Miniconda3 local_channel. see $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
+         [ $? != 0 ] && echo "Error while installing '$pkg' from conda-forge local_channel. see $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
        done
     fi
     [ `uname -s` = Darwin ] && ln -s python3-config python-config #on MacOS, we need python-config to point to the Conda install
@@ -947,7 +947,7 @@ echo "export PYTHONINTERP_ROOT_DIR=\$PYTHONLIBS_ROOT_DIR/bin" >> $env
 echo "ADD_PATH \$PYTHONLIBS_ROOT_DIR/bin" >> $env
 echo "unset PYTHONPATH" >> $env # Pour la CentOS6.5, PYTHONPATH contient le chemin vers python2.6
 
-# Gestion d'une librairie systeme plus recente que miniconda (ex: libtinfo.so.6.0.29 sur Ubuntu 20 et Debian 10), on vire:
+# Gestion d'une librairie systeme plus recente que conda (ex: libtinfo.so.6.0.29 sur Ubuntu 20 et Debian 10), on vire:
 tinfo_conda=`cd $TRUST_ROOT/exec/python/lib 2>/dev/null;ls libtinfo.so.6.* 2>/dev/null | cut -d'.' -f3-5`
 if [ "$tinfo_conda" != "" ]
 then
@@ -1059,7 +1059,7 @@ then
    export TRUST_CC_BASE_EXTP TRUST_cc_BASE_EXTP TRUST_F77_BASE_EXTP
 fi
 
-# Gestion d'une librairie systeme plus recente que miniconda (ex: libstdc++.so.6.0.29 sur Fedora>=34 pour libstdc++.so.6.0.28 dans conda avec libstdcxx-ng=9.3.0), on vire:
+# Gestion d'une librairie systeme plus recente que conda (ex: libstdc++.so.6.0.29 sur Fedora>=34 pour libstdc++.so.6.0.28 dans conda avec libstdcxx-ng=9.3.0), on vire:
 # Le pb se produit au niveau du test Python de l'import MEDCoupling ou d'un editeur comme gedit: GLIBCXX_X.Y.Z not found
 stdcpp_conda=`cd $TRUST_ROOT/exec/python/lib 2>/dev/null;ls libstdc++.so.6.0.* 2>/dev/null | cut -d'.' -f3-6`
 if [ "$stdcpp_conda" != "" ]
@@ -1692,7 +1692,7 @@ then
    for pkg in $pkgs
    do
      echo "Installing $pkg ..."
-     cmd="env MPICH_CC=gcc OMPI_CC=gcc MPICC=$TRUST_cc $TRUST_ROOT/exec/python/bin/pip install $TRUST_ROOT/externalpackages/pip/$pkg*.gz 1>$TRUST_ROOT/exec/conda_python.log 2>&1"
+     cmd="env MPICH_CC=gcc OMPI_CC=gcc MPICC=$TRUST_cc TMPDIR=$TRUST_TMP $TRUST_ROOT/exec/python/bin/pip install $TRUST_ROOT/externalpackages/pip/$pkg*.gz 1>$TRUST_ROOT/exec/conda_python.log 2>&1"
      eval $cmd
      if [ $? != 0 ]
      then
