[Kokkos] Becomes a mandatory (TRUST_USE_KOKKOS=1) prerequisite of TRUST. Moved under ThirdPart directory

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -651,22 +651,21 @@ case $arch in
            export PATH=$PATH:$NVHPC/bin # PATH to $INSTALL/nvhpc-$SDK_VERSION/Linux_x86_64/$SDK_VERSION/compilers/bin
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NVHPC/lib # PATH to $INSTALL/nvhpc-$SDK_VERSION/Linux_x86_64/$SDK_VERSION/compilers/lib
         fi
-         nvc++ -help 1>/dev/null 2>&1
+        nvc++ -help 1>/dev/null 2>&1
         [ $? != 0 ] && echo "Erreur, nvc++ not installed." && exit -1
-     else
-        # If Kokkos requested without OpenMP, put nvcc_wrapper in priority
-        if [ "$TRUST_USE_KOKKOS" = 1 ]
-        then
-           TRUST_CC_BASE="nvcc_wrapper "$TRUST_CC_BASE
-           TRUST_F77_BASE="gfortran "$TRUST_F77_BASE
-           TRUST_cc_BASE="gcc "$TRUST_cc_BASE
-
-           # Check already done in configure, but who knows ...
-           nvcc_wrapper --help 1>/dev/null 2>&1
-           [ $? != 0 ] && echo "Kokkos: error, nvc_wrapper not correctly installed!" && exit -1
-        fi
+#     else
+#        # If Kokkos requested without OpenMP, put nvcc_wrapper in priority
+#        if [ "$TRUST_USE_KOKKOS" = 1 ]
+#        then
+#           TRUST_CC_BASE="nvcc_wrapper "$TRUST_CC_BASE
+#           TRUST_F77_BASE="gfortran "$TRUST_F77_BASE
+#           TRUST_cc_BASE="gcc "$TRUST_cc_BASE
+#
+#           # Check already done in configure, but who knows ...
+#           nvcc_wrapper --help 1>/dev/null 2>&1
+#           [ $? != 0 ] && echo "Kokkos: error, nvc_wrapper not correctly installed!" && exit -1
+#        fi
      fi
-
 	fi
 	# Support compilateur cray et AOMP de AMD: https://github.com/ROCm-Developer-Tools/aomp/blob/aomp-dev/docs/UBUNTUINSTALL.md
 	if [ "$TRUST_USE_ROCM" = 1 ] && [ "$TRUST_USE_OPENMP" = 1 ]
@@ -2279,24 +2278,12 @@ LINK_MALIB = $LINK_MALIB" > $tmp
 
    # On supprime -DNDEBUG
    Defines=${Defines% -DNDEBUG}
-   # On remplace -O par -g
-   O=`echo $CppFlags | awk '{print $1}'`
-   CppFlags="-g -O0"${CppFlags#$O}
+   # On remplace -O? par -g
+   F77Flags=`echo $F77Flags | sed "1,$ s?-O[0-9]?-g?g"`
+   ccFLAGS=`echo $ccFLAGS | sed "1,$ s?-O[0-9]?-g?g"`
+   CppFlags=`echo $CppFlags | sed "1,$ s?-O[0-9]?-g -O0?g"`
    ### Sur gcc >= 11, -g utilise dwarf5 qui empeche addr2line des versions < 2.35.2 de binutils de convertir les adresses des binaires en numero ligne du code source
    [[ $(echo $TRUST_VERSION_GNU | cut -d '.' -f 1) -ge 11 ]] && CppFlags=${CppFlags/-g /-gdwarf-4 }
-   O=`echo $F77Flags | awk '{print $1}'`
-   F77Flags="-g"${F77Flags#$O}
-   # 16/03/2010: Ajout de -fbounds-check en debug sur gfortran
-   # D'apres http://gcc.gnu.org/bugzilla/show_bug.cgi?id=33745 -fbounds-check ne marche pas bien pour gfortran ancien
-   # On a eu des problemes sur 4.0.1 (peyrolle: TAB(N,*) annonce un depassement tableau, TAB(N,M) non) et 4.1 (castor)
-   # On a aussi un pb sur Fedora 18 At line 1 of file pilaenv.f : Fortran runtime error: Actual string length is shorter than the declared one for... (MC2 en debug)
-   # 19-09-2016: probleme avec clang sur cas test Lire_unv => on commente
-   #if [ $TRUST_F77_BASE != ${TRUST_F77_BASE%gfortran} ] && [ "`$TRUST_F77_BASE -v 2>&1 | awk '/gcc / && /version / {print ($3>=4.2?1:0)}'`" = 1 ] && [ "`grep 'Fedora release' /etc/issue`" = "" ]
-   #then
-   #   F77Flags=$F77Flags" -fbounds-check"
-   #fi
-   O=`echo $ccFLAGS | awk '{print $1}'`
-   ccFLAGS="-g"${ccFLAGS#$O}
    #############################
    # Creation du fichier profile
    #############################
@@ -2318,13 +2305,13 @@ LINK_MALIB = $LINK_MALIB" > $tmp
       # Avec icpc l'inlining ne se fait pas avec -pg on le force:
       [ "`basename $TRUST_CC_BASE`" = icpc ] && option_profile=$option_profile" -inline-forceinline"
    fi
-   echo $ECHO_OPTS "1,$ s?$O?-g $option_profile $O?g\nw" | ed $tmp 1>/dev/null 2>&1
+   echo $ECHO_OPTS "1,$ s?-O?-g $option_profile -O?g\nw" | ed $tmp 1>/dev/null 2>&1
    # Pour le link il faut -pg !
    echo $ECHO_OPTS "1,$ s?SYSLIBS =?SYSLIBS = $option_profile?g\nw" | ed $tmp 1>/dev/null 2>&1
 
    suffixe2=$TRUST_ARCH_CC${suffixe#$TRUST_ARCH_CC}"_pg"
    update_file $tmp make.$suffixe2
-   O="-g"
+   #O="-g"
    ##############################
    # Creation du fichier coverage
    ##############################
