[Kokkos] Try to build Kokkos with nvc++ to have hybrid OpenMP/Kokkos

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -632,37 +632,40 @@ case $arch in
 	TRUST_F77_BASE="frt ifx ifort armflang   "$cuda"gfortran gfortran"
 	TRUST_cc_BASE=" fc  icx icc   armclang   "$cuda"gcc      gcc"
 	# Support compilateur NVidia:
-	if [ "$TRUST_USE_CUDA" = 1 ] || [ "$TRUST_USE_OPENMP" = 1 ]
+	if [ "$TRUST_USE_CUDA" = 1 ]
 	then
-	   TRUST_CC_BASE="nvc++ "$TRUST_CC_BASE
-	   TRUST_F77_BASE="nvfortran "$TRUST_F77_BASE
-	   TRUST_cc_BASE="nvc "$TRUST_cc_BASE
-	   # Si n'est pas dans le PATH, on download NVHPC (attention pas encore teste). Utile sur Fedora CEA:
-	   # Normalement, sur Ubuntu on charge le PATH du module NVHPC
-	   nvc++ -help 1>/dev/null 2>&1
-	   if [ $? != 0 ]
+	   if [ "$TRUST_USE_OPENMP" = 1 ]
 	   then
-	      source ../env_src/gpu/install_nvhpc_sdk_toolkit.sh
-	      # Attention, on met NVHPC en dernier car on prendre de preference le nvcc du CUDA Toolkit:
-	      echo "ADD_PATH_AFTER $NVHPC/bin" >>$env
-	      echo "ADD_LD_LIBRARY_PATH_AFTER $NVHPC/lib" >>$env
-	      export PATH=$PATH:$NVHPC/bin # PATH to $INSTALL/nvhpc-$SDK_VERSION/Linux_x86_64/$SDK_VERSION/compilers/bin
-	      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NVHPC/lib # PATH to $INSTALL/nvhpc-$SDK_VERSION/Linux_x86_64/$SDK_VERSION/compilers/lib
-	   fi
-	   nvc++ -help 1>/dev/null 2>&1
-	   [ $? != 0 ] && echo "Erreur, nvc++ not installed." && exit -1
+        TRUST_CC_BASE="nvc++ "$TRUST_CC_BASE
+        TRUST_F77_BASE="nvfortran "$TRUST_F77_BASE
+        TRUST_cc_BASE="nvc "$TRUST_cc_BASE
+        # Si n'est pas dans le PATH, on download NVHPC (attention pas encore teste). Utile sur Fedora CEA:
+        # Normalement, sur Ubuntu on charge le PATH du module NVHPC
+        nvc++ -help 1>/dev/null 2>&1
+        if [ $? != 0 ]
+        then
+           source ../env_src/gpu/install_nvhpc_sdk_toolkit.sh
+           # Attention, on met NVHPC en dernier car on prendre de preference le nvcc du CUDA Toolkit:
+           echo "ADD_PATH_AFTER $NVHPC/bin" >>$env
+           echo "ADD_LD_LIBRARY_PATH_AFTER $NVHPC/lib" >>$env
+           export PATH=$PATH:$NVHPC/bin # PATH to $INSTALL/nvhpc-$SDK_VERSION/Linux_x86_64/$SDK_VERSION/compilers/bin
+           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NVHPC/lib # PATH to $INSTALL/nvhpc-$SDK_VERSION/Linux_x86_64/$SDK_VERSION/compilers/lib
+        fi
+         nvc++ -help 1>/dev/null 2>&1
+        [ $? != 0 ] && echo "Erreur, nvc++ not installed." && exit -1
+     else
+        # If Kokkos requested without OpenMP, put nvcc_wrapper in priority
+        if [ "$TRUST_USE_KOKKOS" = 1 ]
+        then
+           TRUST_CC_BASE="nvcc_wrapper "$TRUST_CC_BASE
+           TRUST_F77_BASE="gfortran "$TRUST_F77_BASE
+           TRUST_cc_BASE="gcc "$TRUST_cc_BASE
 
-	   # If Kokkos requested, put nvcc_wrapper in priority
-	   if [ "$TRUST_USE_KOKKOS" = 1 ]
-	   then
-            TRUST_CC_BASE="nvcc_wrapper "$TRUST_CC_BASE
-            TRUST_F77_BASE="gfortran "$TRUST_F77_BASE
-            TRUST_cc_BASE="gcc "$TRUST_cc_BASE
-
-            # Check already done in configure, but who knows ...
-            nvcc_wrapper --help 1>/dev/null 2>&1
-            [ $? != 0 ] && echo "Kokkos: error, nvc_wrapper not correctly installed!" && exit -1
-	   fi
+           # Check already done in configure, but who knows ...
+           nvcc_wrapper --help 1>/dev/null 2>&1
+           [ $? != 0 ] && echo "Kokkos: error, nvc_wrapper not correctly installed!" && exit -1
+        fi
+     fi
 
 	fi
 	# Support compilateur cray et AOMP de AMD: https://github.com/ROCm-Developer-Tools/aomp/blob/aomp-dev/docs/UBUNTUINSTALL.md
@@ -1815,7 +1818,15 @@ case $TRUST_ARCH_CC in
    linux_pgCC|linux_nvc++) TRUST_SUPPORTED=1
         m="# TMPDIR ?";e="TMPDIR=\"$TRUST_TMP\" && export TMPDIR";ecrit $m"|"$e"|"$env # Plantage vus avec /tmp par defaut
         Defines="-D_COMPILE_AVEC_PGCC"
-        CppFlags="-O3 -fPIC -Ktrap=fp -Kieee -noswitcherror" # -Ktrap=fp evitent des soucis Arithmetic Exceptions...
+        CppFlags=""
+        if [ "$TRUST_USE_KOKKOS" = 1 ]
+        then
+           CppFlags="-cuda" # nvc++ compile cuda code to avoid use of "nvcc -ccbin=nvc++"
+           # Attention -mp=gpu -gpu=nordc ne marche pas sur le GPU !!! Voir: https://forums.developer.nvidia.com/t/openmp-offload-w-cuda-interop-undefined-reference-to-fatbinwrap-nv-module-id/253051
+           # Donc on active Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON au niveau de Kokkos
+           STDCPP="c++17"   # For Kokkos 4.x (attention C++17: NVHPC 23.5 OK, NVHPC 23.9 KO sur template !)
+        fi
+        CppFlags=$CppFlags" -O3 -fPIC -Ktrap=fp -Kieee -noswitcherror" # -Ktrap=fp evitent des soucis Arithmetic Exceptions...
         CppFlags=$CppFlags" -std=$STDCPP -Wno-long-long -Wall -Wshadow -Wextra -Wno-unused-parameter -Werror --display_error_number --diag_suppress1 --diag_suppress185" #--diag_suppress111 si on veut supprimer le warning "statement is unreachable"
         CppFlags=$CppFlags" -Wunused-variable" # Flag qui detecte tous les objets C++ non utilises
         #CppFlags=$CppFlags" -Minfo=accel -Minfo=mp -Minfo=loop" # Info au build ou NVCOMPILER_ACC_NOTIFY ?
