Commit for a Release beta v1.7.5_beta1 version.

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -1180,13 +1180,14 @@ else
 	       # Pb decouvert sur machine is202803 et ioulia : il ne faut pas inclure mpi++.h dans le mpi.h sinon warning qui font des erreurs avec -Wall -Werror:
 	       [ -f `dirname $mpiCC`/mpicxx ] && COMFLAGS=$COMFLAGS" -DMPICH_SKIP_MPICXX"
                # Test du MPI_Abort en parallel (KO avec openmpi 1.10.3 1.10.4 1.10.5)
-               echo $ECHO_OPTS "# Check `basename $mpiCC` (mpiAbort.log file): "
-               echo $mpiCC -o ./test_mpi $rep_test_mpi/test_abort_mpi.cpp
-               $mpiCC -o ./test_mpi $rep_test_mpi/test_abort_mpi.cpp 1>mpiAbort.log 2>&1
-               err=$?
-               [ $err = 0 ] && run_test_mpi_par 1>>mpiAbort.log 2>&1
-               OK $err
-               [ $err = 1 ] && mpi_detecte=0 && echo "Problem with MPI_ABORT of `mpirun --version | head -n 1`. Upgrade of MPI version."
+               # desactive car pb en soumission de job hors frontale
+               #echo $ECHO_OPTS "# Check `basename $mpiCC` (mpiAbort.log file): "
+               #echo $mpiCC -o ./test_mpi $rep_test_mpi/test_abort_mpi.cpp
+               #$mpiCC -o ./test_mpi $rep_test_mpi/test_abort_mpi.cpp 1>mpiAbort.log 2>&1
+               #err=$?
+               #[ $err = 0 ] && run_test_mpi_par 1>>mpiAbort.log 2>&1
+               #OK $err
+               #[ $err = 1 ] && mpi_detecte=0 && echo "Problem with MPI_ABORT of `mpirun --version | head -n 1`. Upgrade of MPI version."
 	    fi	
 	 fi
       fi
@@ -1214,6 +1215,8 @@ else
       # MPI_ROOT="$TRUST_ROOT/lib/src/LIBMPI/openmpi" && [ "$TRUST_FORCE_PROVIDED_MPICH" = 1 ] && MPI_ROOT="$TRUST_ROOT/lib/src/LIBMPI/mpich"
       # New 1.6.9 -> MPICH by default instead of OpenMPI (hangs on several cases, eg: UJV_32 on gudy)
       MPI_ROOT="$TRUST_ROOT/lib/src/LIBMPI/mpich"
+      # New 1.7.5 -> OpenMPI by default instead of MPICH (2.0.2 valgrind free)
+      #MPI_ROOT="$TRUST_ROOT/lib/src/LIBMPI/openmpi"
       if [ "$TRUST_FORCE_PROVIDED_OPENMPI" = 1 ] || [ "$TRUST_FORCE_OLD_OPENMPI" = 1 ] || [ "$TRUST_FORCE_LATEST_OPENMPI" = 1 ]
       then
          MPI_ROOT="$TRUST_ROOT/lib/src/LIBMPI/openmpi"
