[Conda] Faster install: all packages in one

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -841,19 +841,31 @@ then
     conda_installer=`cd $TRUST_ROOT/externalpackages/Miniconda;ls Mini*3*-$system"-"$model.sh`
     echo "Trying to install $conda_installer"
     # PL: Change le TMPDIR car par defaut sur /tmp et pb si mis a noexec
-    TMPDIR=$TRUST_TMP $TRUST_ROOT/externalpackages/Miniconda/./$conda_installer -p $TRUST_ROOT/exec/python/ -b 1>$TRUST_ROOT/exec/conda_python.log 2>&1
+    TMPDIR=$TRUST_TMP $TRUST_ROOT/externalpackages/Miniconda/$conda_installer -p $TRUST_ROOT/exec/python/ -b 1>$TRUST_ROOT/exec/conda_python.log 2>&1
     [ $? != 0 ] && echo "Error while installing $conda_installer. See $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED && exit -1
 
     # Installing packages from local channel
     cd $TRUST_ROOT/exec/python/bin
     # Vu sur certaines machines conda_installer ne modifie pas correctement le chemin vers python
     sed -i "s?/usr/bin/env python?$PWD/python?" ./conda
-    for pkg in $pkgs
-    do
-      echo "Installing $pkg ... "
-      ./conda install $local_channel $pkg -y 1>>$TRUST_ROOT/exec/conda_python.log 2>&1
-      [ $? != 0 ] && echo "Error while installing '$pkg' from Miniconda3 local_channel. see $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
-    done
+    FASTER_CONDA_INSTALL=1
+    if [ "$FASTER_CONDA_INSTALL" = 1 ]
+    then
+       #time ./conda install $local_channel mamba conda=4.9.2 libstdcxx-ng=9.1.0 openssl=1.1.1h || exit -1
+       for pkg in $pkgs
+       do
+          echo "Installing $pkg..."
+       done
+       ./conda install $local_channel $pkgs -y 1>>$TRUST_ROOT/exec/conda_python.log 2>&1
+       [ $? != 0 ] && echo "Error while installing packages from Miniconda3 local_channel. See $TRUST_ROOT/exec/conda_python.log" && exit -1
+    else
+       for pkg in $pkgs
+       do
+         echo "Installing $pkg ... "
+         time ./conda install $local_channel $pkg -y 1>>$TRUST_ROOT/exec/conda_python.log 2>&1
+         [ $? != 0 ] && echo "Error while installing '$pkg' from Miniconda3 local_channel. see $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
+       done
+    fi
 	[ `uname -s` = Darwin ] && ln -s python3-config python-config #on MacOS, we need python-config to point to the Conda install
     cd - 1>/dev/null 2>&1
     # If a package has not been correctly installed, we exit with an error
