MiniConda3!
+ removing obsolote comment in configurer_env

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -888,7 +888,8 @@ then
 
    INSTALL_OK=1 
    # list of packages already-installed/to-install in conda
-   pkgs="pyqt nomkl numpy fontconfig matplotlib jsonschema swig cmake"
+   #pkgs="pyqt nomkl numpy matplotlib swig cmake"
+   pkgs="swig cmake"
    for pkg in $pkgs ; do
      [ "`$TRUST_ROOT/exec/python/bin/conda list | grep $pkg`" = "" ] && INSTALL_OK=0
    done
@@ -909,18 +910,21 @@ then
     [ -d $TRUST_ROOT/exec/python ] && rm -rf $TRUST_ROOT/exec/python
 
     # Then we install miniconda and the different packages
-    echo "Trying to install Miniconda2-4.6.14-Linux-x86_64.sh"
-    $TRUST_ROOT/externalpackages/Miniconda/./Miniconda2-4.6.14-Linux-x86_64.sh -p $TRUST_ROOT/exec/python/ -b 1>$TRUST_ROOT/exec/conda_python.log 2>&1
-    [ $? != 0 ] && echo "Error while installing Miniconda2-4.6.14-Linux-x86_64.sh. See $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
+    echo "Trying to install Miniconda3.7-Linux-x86_64.sh"
+    $TRUST_ROOT/externalpackages/Miniconda/./Miniconda3.7-Linux-x86_64.sh -p $TRUST_ROOT/exec/python/ -b 1>$TRUST_ROOT/exec/conda_python.log 2>&1
+    [ $? != 0 ] && echo "Error while installing Miniconda3.7-Linux-x86_64.sh. See $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
 
     # Installing packages from local channel
     cd $TRUST_ROOT/exec/python/bin
 
-    pkgs="pyqt=4 nomkl numpy fontconfig=2.12.1 matplotlib jsonschema swig cmake"
+    #pkgs="pyqt=4 nomkl numpy matplotlib swig cmake"
+    pkgs="swig=3.0.12 cmake=3.14"
     for pkg in $pkgs
     do
       echo "Installing $pkg ... "
-      ./conda install -c file://$TRUST_ROOT/externalpackages/Miniconda/local_channel --override-channels $pkg -y  1>>$TRUST_ROOT/exec/conda_python.log 2>&1
+      #./conda install -c file://$TRUST_ROOT/externalpackages/Miniconda/local_channel --override-channels $pkg -y  1>>$TRUST_ROOT/exec/conda_python.log 2>&1i
+      # Installing from the web for now ...
+      ./conda install $pkg -y  1>>$TRUST_ROOT/exec/conda_python.log 2>&1
       [ $? != 0 ] && echo "Error while installing '$pkg' from Miniconda2 local_channel. see $TRUST_ROOT/exec/conda_python.log" >> $TRUST_ROOT/NON_INSTALLED
     done
     cd -
@@ -934,7 +938,6 @@ echo "export PYTHONINTERP_ROOT_DIR=\$PYTHONLIBS_ROOT_DIR/bin" >> $env
 echo "ADD_PATH \$PYTHONLIBS_ROOT_DIR/bin" >> $env
 echo "unset PYTHONPATH" >> $env # Pour la CentOS6.5, PYTHONPATH contient le chemin vers python2.6
 # Ligne commenté à cause des warnings gdb 
-#echo "ADD_PYTHONPATH \$PYTHONLIBS_ROOT_DIR/lib/python`$TRUST_ROOT/exec/python/bin/python -c "import sys; print sys.version[:3]"`/site-packages" >> $env
 
 ####################
 # Compilateurs C/C++
