[NVidia] Multiples corrections pour compilateur NVidia (make ctest_optim OK) et utilisation d'altair pour un build OpenMP+Cuda+NVidia pour test offload GPU

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -638,13 +638,16 @@ case $arch in
 	TRUST_EDITOR="gedit nedit kate kedit xemacs xedit emacs"
 	# On met Intel en 1er/GNU car plus rapide que GNU
 	cuda="" && [ "$TRUST_USE_CUDA" = 1 ] && cuda="cuda-" # Uniquement si on demande Cuda, recherche en priorite des wrappers pour les compilateurs GNU
-	# Pas prudent de mettre les compilateurs NVidia en premier... Sauf si -openmp ou -openacc ?
-        #TRUST_CC_BASE=" nvc++     FCC icpc  armclang++ "$cuda"g++      g++"
-	#TRUST_F77_BASE="nvfortran frt ifort armflang   "$cuda"gfortran gfortran"
-	#TRUST_cc_BASE=" nvc       fc  icc   armclang   "$cuda"gcc      gcc"
 	TRUST_CC_BASE=" crayCC  FCC icpc  armclang++ "$cuda"g++      g++"
 	TRUST_F77_BASE="crayftn frt ifort armflang   "$cuda"gfortran gfortran"
 	TRUST_cc_BASE=" craycc  fc  icc   armclang   "$cuda"gcc      gcc"
+	if [ "$TRUST_USE_OPENMP" = 1 ]
+	then
+    	   # On place les compilateurs NVidia en premier pour l'offloading GPU avec OpenMP:
+	   TRUST_CC_BASE="nvc++ "$TRUST_CC_BASE
+    	   TRUST_F77_BASE="nvfortran "$TRUST_F77_BASE
+	   TRUST_cc_BASE="nvc "$TRUST_cc_BASE
+	fi
 	# On rajoute les autres compilateurs
 	TRUST_CC_BASE=$TRUST_CC_BASE" pgCC"
 	TRUST_F77_BASE=$TRUST_F77_BASE" pgf90 f90 pgf77 f77"
@@ -1015,7 +1018,17 @@ m="# Path to optimized BLAS";e="TRUST_BLAS_LAPACK=\"$TRUST_BLAS_LAPACK\" && expo
 ########
 if [ "$TRUST_USE_CUDA" = 1 ]
 then
-   [ "$TRUST_DISABLE_PETSC" = 1 ] && echo "Error, you need PETSc with -cuda option to build AmgXWrapper/AmgX." && exit -1
+   TRUST_USE_AMGX=1
+   if [ ${TRUST_CC_BASE%nvc++} != $TRUST_CC_BASE ] # Plusieurs librairies ne compilent pas encore avec NVidia HPC/SDK
+   then
+      TRUST_USE_AMGX=0 # AmgX ne compile toujours avec nvc++ (voir version recente d'AmgX) 
+      [ "$TRUST_DISABLE_PETSC"    != 1 ] && echo "Add -disable-petsc with nvc++ compiler"    && exit=-1  
+      [ "$TRUST_DISABLE_VC"       != 1 ] && echo "Add -disable-vc with nvc++ compiler"       && exit=-1  
+      [ "$TRUST_FORCE_SYSTEM_MPI" != 1 ] && echo "Add -force_system_mpi with nvc++ compiler" && exit=-1
+      [ "$exit" = -1 ] && exit $exit
+   fi   
+   e="TRUST_USE_AMGX=\"$TRUST_USE_AMGX\" && export TRUST_USE_AMGX" && m="# Use AmgX ?" && ecrit $m"|"$e"|"$env && eval $e
+   [ "$TRUST_USE_AMGX" = 1 ] && [ "$TRUST_DISABLE_PETSC" = 1 ] && echo "Error, you need PETSc with -cuda option to build AmgXWrapper/AmgX." && exit -1
    check_nvidia_cuda
    [ "$CUDA_ROOT" = "" ] && echo "CUDA libraries not found!" && exit -1
    m="# PATH to CUDA";
@@ -1956,16 +1969,19 @@ then
    # Test offloading:
    if [ "$openmp_target" != "" ]
    then
-      echo "int main()
+      cmd="$TRUST_CC $openmp $openmp_target -o offload_openmp offload_openmp.cpp"
+      echo "#include <iostream>
+int main()
 {
 double a[3];
 double b[3];
 #pragma omp target
    for (int i=0;i<3;i++)
       a[i]=b[i]+1;
-
+   for (int i=0;i<3;i++)
+      std::cout << a[i] << std::endl;      
   return 0;
-}" > offload_openmp.cpp && $TRUST_CC $openmp $openmp_target -o offload_openmp offload_openmp.cpp && ./offload_openmp
+}" > offload_openmp.cpp && echo $cmd && eval $cmd #&& ./offload_openmp
       if [ $? != 0 ]
       then
          echo "Error, $TRUST_CC_BASE compiler doesn't support OpenMP offloading."
