[Install] Run GPU tests only if quota available.

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -2001,27 +2001,34 @@ then
    # Installation NVIDIA Samples
    #############################
    echo $ECHO_OPTS "Is it a double precision NVIDIA card ? \c"
-   # Test de la carte:
+   # Compilation d'un binaire Cuda et test de la carte:
    (
        source ../env_TRUST.sh 1>/dev/null 2>&1
        LD_LIBRARY_PATH=$CUDA_LIB:$LD_LIBRARY_PATH
        rm -r -f nvc_get_devices
        tar xfz $TRUST_ROOT/externalpackages/AmgX/nvc_get_devices.tgz
-       cd nvc_get_devices && ./build.sh
+       cd nvc_get_devices && ./build.sh || exit -1
+       # Test eventuel (plus bloquant si echec):
        export exec=`pwd`/nvc_get_devices
-       trust -gpu dummy_file 1>>$TRUST_ENV/card.log &
-       $TRUST_ROOT/bin/KSH/wait_for $! 600 # Pour eviter blocage
+       rm -f $TRUST_ENV/card.log
+       trust -gpu dummy_file 1>$TRUST_ENV/card.log 2>&1 &
+       $TRUST_ROOT/bin/KSH/wait_for $! 60 # Pour eviter blocage
    )
-   COMPUTE_CAPABILITY="`awk '/apability/ {print $NF}' $TRUST_ENV/card.log | head -1`"
-   # On ne supporte que les cartes double precision
-   TRUST_USE_CUDA="`echo $COMPUTE_CAPABILITY | awk '{if ($1>=1.3) print 1;else print 0}'`"
-   if [ "$TRUST_USE_CUDA" = 0 ]
+   COMPUTE_CAPABILITY="`awk '/apability/ {print $NF}' $TRUST_ENV/card.log 2>/dev/null | head -1`"
+   if [ "$COMPUTE_CAPABILITY" != "" ]
    then
-      echo "No. See error:"
-      cat $TRUST_ENV/card.log
-      exit -1
+      # On ne supporte que les cartes double precision
+      TRUST_USE_CUDA="`echo $COMPUTE_CAPABILITY | awk '{if ($1>=1.3) print 1;else print 0}'`"
+      if [ "$TRUST_USE_CUDA" = 0 ]
+      then
+         echo "No. See error:"
+         cat $TRUST_ENV/card.log
+         exit -1
+      else
+         awk '/Device 0/ {print "Yes. The NVIDIA card is "$0}' $TRUST_ENV/card.log
+      fi
    else
-      awk '/Device 0/ {print "Yes. The NVIDIA card is "$0}' $TRUST_ENV/card.log
+      echo "Not tested."
    fi
    m="# TRUST will use CUDA ?";e="TRUST_USE_CUDA=\"$TRUST_USE_CUDA\" && export TRUST_USE_CUDA";ecrit $m"|"$e"|"$env
    Defines=$Defines" -DTRUST_USE_CUDA -DPETSC_SKIP_COMPLEX"
