[Miniconda] Option -without-conda to avoid using Miniconda.
+ rely exclusively on system prerequisites

diff --git a/env_src/configurer_env b/env_src/configurer_env
--- a/env_src/configurer_env
+++ b/env_src/configurer_env
@@ -849,56 +849,67 @@ local_channel="-c file://$TRUST_ROOT/externalpackages/Miniconda/local_channel --
 
 if [ -d $TRUST_ROOT/exec/python/bin ] && [ -f $TRUST_ROOT/exec/python/bin/conda ]
 then
-   # check of python version
-   PYTHON_VERSION_OK=`$TRUST_ROOT/exec/python/bin/python --version 2>&1 | awk '/Python/ {split($2,a,".");v=a[1]*100+a[2]*10+a[3];print (v==379||v==376?1:0)}'`
-   PYTHON_TEST_OK=1 && [ "`$TRUST_ROOT/exec/python/bin/python ./test.py 1>/dev/null 2>&1;echo $?`" != 0 ] && PYTHON_TEST_OK=0
-   INSTALL_OK=1
-
-   # list of packages already-installed/to-install in conda, we ignore mpi4py since installed with pip
-   $TRUST_ROOT/exec/python/bin/conda list | grep -v mpi4py | grep -v coolprop > conda_list.check
-   if [ "$system" = "Linux" ] && [ $model = "x86_64" ] #&& [ -f $TRUST_ROOT/exec/conda_list.ref ]
-   then
-      # Strict check of conda packages
-      if [ "$TRUST_DISABLE_JUPYTER" != 1 ]
-      then
-         cat $TRUST_ROOT/externalpackages/Miniconda/conda_list_ref | sed "s?TRUSTR?$TRUST_ROOT?g" | cut -f1 -d',' > conda_list.ref
-      else
-         cat $TRUST_ROOT/externalpackages/Miniconda/conda_list_ref | sed "s?TRUSTR?$TRUST_ROOT?g" | grep -v jupyter > conda_list.ref
-      fi
-
-      if [ `diff conda_list.ref conda_list.check 1>/dev/null 2>&1; echo $?` != 0 ]
-      then
-         echo "# The current miniconda install contains some supplementary or missing packages, we clean it..."
-         INSTALL_OK=0
-      else
-         rm -f conda_list.ref
-      fi
+   if [ "$TRUST_WITHOUT_CONDA" = "1" ]; then
+       echo "WARNING: Option without CONDA requested ... cleaning previous installation ..."
+       rm -rf $TRUST_ROOT/exec/python
+       echo "         Done."
+       INSTALL_CONDA=0
    else
-      # pour mac, on verifie pas strictement le numero de version python, par contre on teste que ce python fonctionne
-      [ "$system" = "MacOSX" ] && PYTHON_VERSION_OK=1
-      for pkg in $pkgs
-      do
-        pkg=`echo $pkg | awk -F= '{print $1}'` # Pour ne pas avoir le numero de version
-        [ "`grep $pkg conda_list.check`" = "" ] && INSTALL_OK=0
-      done
-   fi
-   rm -f conda_list.check
-   if [ "$PYTHON_VERSION_OK" != 1 ] || [ "$PYTHON_TEST_OK" != 1 ] || [ "$INSTALL_OK" != 1 ]
-   then
-      INSTALL_CONDA=1
-   else
-      echo "# The current install of python, python packages, swig and cmake from miniconda seems OK... we skip it"
-   fi
+       # check of python version
+       PYTHON_VERSION_OK=`$TRUST_ROOT/exec/python/bin/python --version 2>&1 | awk '/Python/ {split($2,a,".");v=a[1]*100+a[2]*10+a[3];print (v==379||v==376?1:0)}'`
+       PYTHON_TEST_OK=1 && [ "`$TRUST_ROOT/exec/python/bin/python ./test.py 1>/dev/null 2>&1;echo $?`" != 0 ] && PYTHON_TEST_OK=0
+       INSTALL_OK=1
+    
+       # list of packages already-installed/to-install in conda, we ignore mpi4py since installed with pip
+       $TRUST_ROOT/exec/python/bin/conda list | grep -v mpi4py | grep -v coolprop > conda_list.check
+       if [ "$system" = "Linux" ] && [ $model = "x86_64" ] #&& [ -f $TRUST_ROOT/exec/conda_list.ref ]
+       then
+          # Strict check of conda packages
+          if [ "$TRUST_DISABLE_JUPYTER" != 1 ]
+          then
+             cat $TRUST_ROOT/externalpackages/Miniconda/conda_list_ref | sed "s?TRUSTR?$TRUST_ROOT?g" | cut -f1 -d',' > conda_list.ref
+          else
+             cat $TRUST_ROOT/externalpackages/Miniconda/conda_list_ref | sed "s?TRUSTR?$TRUST_ROOT?g" | grep -v jupyter > conda_list.ref
+          fi
+    
+          if [ `diff conda_list.ref conda_list.check 1>/dev/null 2>&1; echo $?` != 0 ]
+          then
+             echo "# The current miniconda install contains some supplementary or missing packages, we clean it..."
+             INSTALL_OK=0
+          else
+             rm -f conda_list.ref
+          fi
+       else
+          # pour mac, on verifie pas strictement le numero de version python, par contre on teste que ce python fonctionne
+          [ "$system" = "MacOSX" ] && PYTHON_VERSION_OK=1
+          for pkg in $pkgs
+          do
+            pkg=`echo $pkg | awk -F= '{print $1}'` # Pour ne pas avoir le numero de version
+            [ "`grep $pkg conda_list.check`" = "" ] && INSTALL_OK=0
+          done
+       fi
+       rm -f conda_list.check
+       if [ "$PYTHON_VERSION_OK" != 1 ] || [ "$PYTHON_TEST_OK" != 1 ] || [ "$INSTALL_OK" != 1 ]
+       then
+          INSTALL_CONDA=1
+       else
+          echo "# The current install of python, python packages, swig and cmake from miniconda seems OK... we skip it"
+       fi
+    fi
 else
-   INSTALL_CONDA=1
+   if [ "$TRUST_WITHOUT_CONDA" = "1" ]; then
+      INSTALL_CONDA=0
+   else
+      INSTALL_CONDA=1
+   fi
 fi
 
-if [ "$(uname -a | grep CYGWIN)" != "" ] 
-then
-  INSTALL_CONDA=0
-  mkdir -p $TRUST_ROOT/exec
-  (cd $TRUST_ROOT/exec/; ln -sf $(dirname $(dirname $(which python))) python ) 
-fi
+#if [ "$(uname -a | grep CYGWIN)" != "" ] 
+#then
+#  INSTALL_CONDA=0
+#  mkdir -p $TRUST_ROOT/exec
+#  (cd $TRUST_ROOT/exec/; ln -sf $(dirname $(dirname $(which python))) python ) 
+#fi
 
 if [ "$INSTALL_CONDA" = 1 ]
 then
@@ -938,21 +949,27 @@ then
     cd - 1>/dev/null 2>&1
     # If a package has not been correctly installed, we exit with an error
     [ -f $TRUST_ROOT/NON_INSTALLED ] && [ "`grep Miniconda $TRUST_ROOT/NON_INSTALLED`" != "" ] &&  Display_Missing_packages && exit -1
+else  # INSTALL_CONDA=0 
+    ze_python=`which python`
+    echo "WARNING: Installing without conda - The following (automatically detected) Python will be used and is sym-linked in exec/python/bin:"
+    echo "         $ze_python"
+    mkdir -p $TRUST_ROOT/exec/python/bin
+    ln -nsf $ze_python $TRUST_ROOT/exec/python/bin/python
 fi
+
 # clean of the install folder
-rm -r $TRUST_ROOT/exec/python/pkgs
-mkdir $TRUST_ROOT/exec/python/pkgs
+rm -rf $TRUST_ROOT/exec/python/pkgs
+mkdir -p $TRUST_ROOT/exec/python/pkgs
 # We touch all conda files, otherwise it will be deleted from SCRATCH of clusters (e.g. jean-zay)
 [ "${TRUST_ROOT#*scratch/}" != "$TRUST_ROOT" ] && find $TRUST_ROOT/exec/python -exec touch {} +
 # export PATH
-PYTHON_ROOT=$TRUST_ROOT/exec/python/bin
 echo "export PYTHONLIBS_ROOT_DIR=\$TRUST_ROOT/exec/python" >> $env
 echo "export PYTHONINTERP_ROOT_DIR=\$PYTHONLIBS_ROOT_DIR/bin" >> $env
 echo "ADD_PATH \$PYTHONLIBS_ROOT_DIR/bin" >> $env
 echo "unset PYTHONPATH" >> $env # Pour la CentOS6.5, PYTHONPATH contient le chemin vers python2.6
 
 # Gestion d'une librairie systeme plus recente que miniconda (ex: libtinfo.so.6.0.29 sur Ubuntu 20 et Debian 10), on vire:
-tinfo_conda=`cd $TRUST_ROOT/exec/python/lib;ls libtinfo.so.6.* 2>/dev/null | cut -d'.' -f3-5`
+tinfo_conda=`cd $TRUST_ROOT/exec/python/lib 2>/dev/null;ls libtinfo.so.6.* 2>/dev/null | cut -d'.' -f3-5`
 if [ "$tinfo_conda" != "" ]
 then
     libtinfo_sys=`ls /usr/lib*/libtinfo.so.6.* /usr/lib*/*64-linux-gnu/libtinfo.so.6.* 2>/dev/null | head -1`
@@ -1052,7 +1069,7 @@ fi
 
 # Gestion d'une librairie systeme plus recente que miniconda (ex: libstdc++.so.6.0.29 sur Fedora34 pour libstdc++.so.6.0.28 dans conda avec libstdcxx-ng=9.3.0), on vire:
 # Le pb se produit au niveau du test Python de l'import MEDCoupling ou d'un editeur comme gedit: GLIBCXX_X.Y.Z not found
-stdcpp_conda=`cd $TRUST_ROOT/exec/python/lib;ls libstdc++.so.6.0.* 2>/dev/null | cut -d'.' -f3-6`
+stdcpp_conda=`cd $TRUST_ROOT/exec/python/lib 2>/dev/null;ls libstdc++.so.6.0.* 2>/dev/null | cut -d'.' -f3-6`
 if [ "$stdcpp_conda" != "" ]
 then
     root_gnu=`dirname $TRUST_F77_BASE` && root_gnu=`dirname $root_gnu`
@@ -1521,9 +1538,9 @@ fi
 [ "$TRUST_F77" = "" ] && m="# Path to F77 compiler" && e="TRUST_F77=\"$TRUST_F77_BASE\" && export TRUST_F77" && ecrit $m"|"$e"|"$env && eval $e
 
 ##############################################################
-# Intallation des packages supplementaires avec pip de conda #
+# Intallation des packages supplementaires avec pip          #
 ##############################################################
-pkgs="" # now, we install only mpi4py with pip if mpi enabled, so umpty list
+pkgs="" # now, we install only mpi4py with pip if mpi enabled, so empty list
 if [ "$TRUST_DISABLE_MPI" != 1 ] && [ "$TRUST_DISABLE_MPI4PY" != 1 ]
 then
    pkgs="mpi4py "$pkgs
@@ -1536,18 +1553,21 @@ then
    pip install coolprop
 fi
 
-# ld from conda does not recognize openmpi configuration on TGCC and Fed36 and orcus-intel
-rm_compiler_compat=0 && [ "`grep 'Fedora release 3[6-8]' /etc/fedora-release 2>/dev/null`" != "" ] && rm_compiler_compat=1
-[ "${HOST#orcus}" != $HOST ] && rm_compiler_compat=1  # on orcus, we should remove it
-if [ "${HOST#irene}" != $HOST ] || [ "${HOST#jean-zay}" != $HOST ] || [ "${HOST_BUILD#jean-zay}" != $HOST_BUILD ] || [ "${HOST#topaze}" != $HOST ] || [ "$rm_compiler_compat" = 1 ]
-then
-   rm -rf $TRUST_ROOT/exec/python/compiler_compat && echo "We remove ld from conda on $HOST ..."
-fi
 InstallPipPkgs=0
-for pkg in $pkgs
-do
-  [ "`$TRUST_ROOT/exec/python/bin/conda list | grep $pkg`" = "" ] && InstallPipPkgs=1
-done
+if [ "$TRUST_WITHOUT_CONDA" != "1" ]; then
+    # ld from conda does not recognize openmpi configuration on TGCC and Fed36 and orcus-intel
+    rm_compiler_compat=0 && [ "`grep 'Fedora release 3[6-8]' /etc/fedora-release 2>/dev/null`" != "" ] && rm_compiler_compat=1
+    [ "${HOST#orcus}" != $HOST ] && rm_compiler_compat=1  # on orcus, we should remove it
+    if [ "${HOST#irene}" != $HOST ] || [ "${HOST#jean-zay}" != $HOST ] || [ "${HOST_BUILD#jean-zay}" != $HOST_BUILD ] || [ "${HOST#topaze}" != $HOST ] || [ "$rm_compiler_compat" = 1 ]
+    then
+       rm -rf $TRUST_ROOT/exec/python/compiler_compat && echo "We remove ld from conda on $HOST ..."
+    fi
+    for pkg in $pkgs
+    do
+      [ "`$TRUST_ROOT/exec/python/bin/conda list | grep $pkg`" = "" ] && InstallPipPkgs=1
+    done
+fi
+
 # On desactive en zone (pb de build):
 [ "${HOST#sagittarius}" != $HOST ] && InstallPipPkgs=0
 if [ "$InstallPipPkgs" = 1 ]
