[bttrust #226298] If externalpackages not up to date, display the corresponding commit and version

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -685,18 +685,36 @@ then
    export PATH=$CUDA_BIN:$PATH
 fi
 
-export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES | sed "s/_beta//"`
+export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES`
 if [ "$clean" != "clean" ]
 then
-   [ ! -d externalpackages ] && [ ! -L externalpackages ] && echo "You need to download externalpackages before configuring" && echo "wget ftp://ftp.cea.fr/pub/TRUST/externalpackages/externalpackages-$TRUST_ROOT_VERSION.tar" && exit -1
+   if [ ! -d externalpackages ] && [ ! -L externalpackages ]
+   then
+      extp_commit=`cat bin/gestion_externalpackages/extp.commit`
+      echo "Error: You need to download externalpackages $TRUST_ROOT_VERSION before configuring :"
+      version_extp=$TRUST_ROOT_VERSION
+      [ "`grep beta $version_extp &>/dev/null ; echo $?`" != 0 ] && version_extp="next"
+      echo "   wget ftp://ftp.cea.fr/pub/TRUST/externalpackages/externalpackages-$version_extp.tar"
+      echo " or:"
+      echo "   curl ftp://ftp.cea.fr/pub/TRUST/externalpackages/externalpackages-$version_extp.tar > externalpackages-$version_extp.tar"
+      echo " or if you have access to git, commit: $extp_commit"
+      exit -1
+   fi
    if [ "$TRUST_DISABLE_CHECKS" = 0 ]
    then
       # Gestion externalpackages
       echo "Verify externalpackages..."
       cd $TRUST_ROOT/bin/gestion_externalpackages
       export LC_ALL=C && ./Verify_externalpackages.sh
-      [ $? != 0 ] && echo "" && echo "Error: You need to update externalpackages directory to $TRUST_ROOT_VERSION version" && exit -1
+      err=$?
       cd $TRUST_ROOT
+      if [ $err != 0 ]
+      then
+         extp_commit=`cat bin/gestion_externalpackages/extp.commit`
+         msg="$TRUST_ROOT_VERSION version (if access to git, commit $extp_commit)"
+         echo "Error: You need to update externalpackages directory to $msg"
+         exit -1
+      fi
    else
       echo "Disabling CHECKS, so externalpackages will not be verified."
    fi
