Add Verify_externalpackages.sh to configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -40,7 +40,13 @@ do
 done
 
 [ ! -d externalpackages ] && [ ! -L externalpackages ] && echo "You need to download externalpackages before configuring" && export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES | sed "s/_beta//"`&& echo wget http://downloads.sourceforge.net/project/trust-platform/$TRUST_ROOT_VERSION/externalpackages_$TRUST_ROOT_VERSION.tar && exit -1
+# Gestion externalpackages
+cd $TRUST_ROOT/bin/gestion_externalpackages
+export LC_ALL=C && ./Verify_externalpackages.sh 
+[ $? != 0 ] && export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES | sed "s/_beta//"` && echo "" && echo "Error: You need to update externalpackages directory to $TRUST_ROOT_VERSION version" && exit -1
+cd $TRUST_ROOT
 
+echo " "
 echo "----------------------------------------------------------------------------------------------------------------------------"
 echo "Usage: `basename $0` "
 echo "[-help]                           Print help of the different configure options."
