Option -disable-check added to the TRUST configure tool (Disable checks for external packages)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -40,14 +40,8 @@ do
    fi
 done
 
-[ ! -d externalpackages ] && [ ! -L externalpackages ] && echo "You need to download externalpackages before configuring" && export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES | sed "s/_beta//"`&& echo wget http://downloads.sourceforge.net/project/trust-platform/$TRUST_ROOT_VERSION/externalpackages_$TRUST_ROOT_VERSION.tar && exit -1
-# Gestion externalpackages
-cd $TRUST_ROOT/bin/gestion_externalpackages
-export LC_ALL=C && ./Verify_externalpackages.sh 
-[ $? != 0 ] && export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES | sed "s/_beta//"` && echo "" && echo "Error: You need to update externalpackages directory to $TRUST_ROOT_VERSION version" && exit -1
-cd $TRUST_ROOT
-
-echo " "
+if [ "$1" != "-disable-optionals" ]
+then
 echo "----------------------------------------------------------------------------------------------------------------------------"
 echo "Usage: `basename $0` "
 echo "[-help]                           Print help of the different configure options."
@@ -77,12 +71,14 @@ echo "[-disable-gnuplot]                Disable gnuplot installation and build."
 echo "[-disable-tcl_tk]                 Disable Tcl/Tk detection/installation."
 echo "[-disable-gmsh]                   Disable Gmsh installation and build."
 echo "[-disable-mpiio]                  Disable MPI-IO mode for writing of .xyz binary output file."
+echo "[-disable-check]                  Disable checks for external packages."
 echo "[-without-doc]                    Do not build the documentation."
 echo "[-without-visit]                  Do not install VisIt."
 echo "[-download-visit]                 Download a sequential version of VisIt rather trying to build a parallel version."
 echo "[-download-salome]                Download the Salome `awk -F= '/version_salome=/ {print $2}' env_src/configurer_env` version in the TRUST environment."
 echo "[-clean]                          Clean the packages installed by configure."
 echo "----------------------------------------------------------------------------------------------------------------------------"
+fi
 CC=""
 cc=""
 F77=""
@@ -97,7 +93,7 @@ echo $0 $* "\$"* >> configure.log
 if [ "$1" = "-disable-optionals" ]
 then
  shift
- $0 -disable-ccache -disable-med -disable-medcoupling -disable-petsc -disable-gnuplot -disable-tcl_tk -disable-valgrind -disable-mpi -disable-metis -without-visit -disable-gmsh -without-doc $* 
+ $0 -disable-ccache -disable-med -disable-medcoupling -disable-petsc -disable-gnuplot -disable-tcl_tk -disable-valgrind -disable-mpi -disable-metis -without-visit -disable-gmsh -without-doc -disable-check $* 
  exit $?
 fi
 
@@ -107,12 +103,14 @@ do
   eval $command       
 done
 export TRUST_DISABLE_MPIIO=0
+export TRUST_DISABLE_CHECK=0
 export TRUST_WITHOUT_DOC=0
 export TRUST_WITHOUT_VISIT=0
 export TRUST_DOWNLOAD_VISIT=0
 export TRUST_DOWNLOAD_SALOME=0
 var=env/configure.env && rm -f $var
 echo "$0 called with options: $*"
+
 while [ "$1" != "" ]
 do
    if [ "${1%-help}" != $1 ]
@@ -204,6 +202,10 @@ do
    elif [ "${1#-disable-mpiio}" != "$1" ]
    then
       export TRUST_DISABLE_MPIIO=1 
+       
+   elif [ "${1#-disable-check}" != "$1" ]
+   then
+      export TRUST_DISABLE_CHECK=1 
 
    elif [ "${1#-disable-}" != "$1" ]
    then
@@ -239,12 +241,28 @@ do
    fi
    shift
 done
+
+if [ "$TRUST_DISABLE_CHECK" = 0 ] && [ "$clean" != "clean" ]
+then
+   [ ! -d externalpackages ] && [ ! -L externalpackages ] && echo "You need to download externalpackages before configuring" && export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES | sed "s/_beta//"`&& echo wget http://downloads.sourceforge.net/project/trust-platform/$TRUST_ROOT_VERSION/externalpackages_$TRUST_ROOT_VERSION.tar && exit -1
+   # Gestion externalpackages
+   echo "Verify externalpackages..."
+   cd $TRUST_ROOT/bin/gestion_externalpackages
+   export LC_ALL=C && ./Verify_externalpackages.sh 
+   [ $? != 0 ] && export TRUST_ROOT_VERSION=`awk '/version/ && /Release notes/ {print $4;exit}' $TRUST_ROOT/RELEASE_NOTES | sed "s/_beta//"` && echo "" && echo "Error: You need to update externalpackages directory to $TRUST_ROOT_VERSION version" && exit -1
+   cd $TRUST_ROOT
+elif [ "$clean" != "clean" ]
+then
+   echo "Disabling CHECK, so no verify externalpackages."
+fi
+
 for THIRD_PARTY in $LIST_THIRD_PARTY 
 do
    VAR=TRUST_DISABLE_$THIRD_PARTY
    echo "$VAR=${!VAR} && export $VAR 	# Disable/enable $THIRD_PARTY"  					>> $var 
 done
 echo "TRUST_DISABLE_MPIIO=$TRUST_DISABLE_MPIIO && export TRUST_DISABLE_MPIIO	# Disable/enable MPI-IO mode for writing of binary output file"	>> $var
+echo "TRUST_DISABLE_CHECK=$TRUST_DISABLE_CHECK && export TRUST_DISABLE_CHECK	# Disable/enable checks for external packages"	>> $var
 echo "TRUST_WITHOUT_DOC=$TRUST_WITHOUT_DOC && export TRUST_WITHOUT_DOC		# Disable/enable Documentation"	>> $var
 echo "TRUST_WITHOUT_VISIT=$TRUST_WITHOUT_VISIT && export TRUST_WITHOUT_VISIT	# Disable/enable VisIt" 	>> $var
 echo "TRUST_DOWNLOAD_VISIT=$TRUST_DOWNLOAD_VISIT && export TRUST_DOWNLOAD_VISIT 	# Download or build VisIt" >> $var
