[lata_tools] Fixed and cleaned Lata plugin build

diff --git a/Outils/VisIt/plugins/lata/build_plugin b/Outils/VisIt/plugins/lata/build_plugin
--- a/Outils/VisIt/plugins/lata/build_plugin
+++ b/Outils/VisIt/plugins/lata/build_plugin
@@ -1,94 +1,95 @@
 #!/bin/bash
+
 prepsrc=0
 # On initialise l'environnement
 source $TRUST_ROOT/env_TRUST.sh 1>/dev/null 2>&1
+
+set -e  # Exit on error - after TRUST source!
+
 LATASRC=Outils/lata_tools/src
 local=$TRUST_ROOT/exec/VisIt/bin
 DIR=`dirname $0`
 DIR=`(cd $DIR;pwd)`
 plugin=lata
 
-# Le plugin depuis le Kernel que si la version de VisIt a ete compilee
-#[ "`ls $TRUST_ROOT/exec/VisIt/current/*/bin/engine_par 2>/dev/null`" = "" ] && echo "Sorry, can't update a plugin of a none built VisIt version." && exit 0 
-#[ "$TRUST_DOWNLOAD_VISIT" = 1 ] && echo "Sorry, can't update a plugin of a none built VisIt version." && exit 0
-
-plugin_visit=`ls -rt $TRUST_ROOT/exec/VisIt/current/*/plugins/databases/*$plugin"Data"*.so 2>/dev/null | head -1`
-plugin_kernel=`ls -rt build/CMakeFiles/*/*.o $TRUST_ROOT/$LATASRC/Dtrust_commun/*  $TRUST_ROOT/$LATASRC/Dtrust_compat/*  2>/dev/null | tail -1`
-# ls -l  $plugin_kernel $plugin_visit
-
-if [ "$plugin_kernel" != "" ] && [ "$plugin_visit" != "" ] && [ "$plugin_kernel" -nt "$plugin_visit" ]
-then
-   echo "$plugin plugin is up to date under VisIt Not sure ....."
-#   exit 0
-fi
-
-Build=build
 Build=$TRUST_ROOT/build/Outils/VisIt/plugins/lata/build
-if [ $0 -nt ${Build} ]
-then
-    echo "removing ${Build}"
-    rm -r -f ${Build}
-    #exit -1
+
+#################
+# Clean if needed
+#################
+if [ $0 -nt ${Build} ]; then
+    echo "CLEANING: removing ${Build}"
+    rm -rf ${Build}
 fi
-if [ ! -d ${Build} ]
-    then
+
+#################
+# Generate CMake
+#################
+if [ ! -d ${Build} ]; then
     mkdir -p ${Build}
     cd ${Build}
-    ln -sf $DIR/src/* . 2>/dev/null
-    for i in `cd $TRUST_ROOT/$LATASRC;ls trust_commun/*.cpp 2>/dev/null`
-      do
-      ln -sf $TRUST_ROOT/$LATASRC/$i `basename $i .cpp`.C
+    ln -sf $DIR/src/avtlataFileFormat.* . 2>/dev/null
+    all_srcs=""    # List of all sources for the LATA plugin
+    # Start with lata_tools sources
+    for i in `cd $TRUST_ROOT/$LATASRC;ls trust_commun/*.cpp 2>/dev/null`; do
+      nam=`basename $i .cpp`.C
+      ln -sf $TRUST_ROOT/$LATASRC/$i $nam
+      all_srcs=$all_srcs" "$nam
     done
-    for i in `cd $TRUST_ROOT/$LATASRC;ls trust_commun/*.h 2>/dev/null`
-      do
+    # Make sure templates and headers are there too
+    for i in `cd $TRUST_ROOT/$LATASRC;ls trust_commun/*.h 2>/dev/null`; do
       ln -sf $TRUST_ROOT/$LATASRC/$i `basename $i`
     done
-
+    # Extra sources from TRUST:
+    cd $TRUST_ROOT/Outils/lata_tools; env OUTFILE=${Build}/extra_src make write_extra_src;  cd $Build
+    for i in `cat extra_src`; do
+      nam=`basename $i .cpp`.C
+      ln -sf $i $nam
+      all_srcs=$all_srcs" "$nam
+    done
 
     echo "# Compiling $plugin plugin..."
     # Regroupement des sources du plugin depuis le Kernel:
     MED="-with_med"
     [ ! -f $TRUST_MED_ROOT/lib/libmed.a ] || [ ! -f $TRUST_MEDCOUPLING_ROOT/lib/libmedloader.a ] && MED=""
-    $DIR/src/generate_lata_xml.sh $TRUST_ROOT/$LATASRC $1 $MED
+    $DIR/src/generate_lata_xml.sh "$all_srcs" $MED
 
-   env LD_LIBRARY_PATH=$TRUST_ROOT/exec/python/lib:$LD_LIBRARY_PATH $local/xml2info lata.xml
+   env LD_LIBRARY_PATH=$TRUST_ROOT/exec/python/lib:$LD_LIBRARY_PATH $local/xml2info lata.xml 
 
-   if [ $prepsrc -eq 1 ] 
-   then
+   if [ $prepsrc -eq 1 ]; then
        env LD_LIBRARY_PATH=$TRUST_ROOT/exec/python/lib:$LD_LIBRARY_PATH $local/xml2cmake lata.xml -dv
-       echo "end of preparation, makefile not modified" && exit 0
+       echo "   end of preparation, makefile not modified" && exit 0
    fi
+
    env LD_LIBRARY_PATH=$TRUST_ROOT/exec/python/lib:$LD_LIBRARY_PATH $local/xml2cmake  lata.xml
    dlocal=`dirname $local`
-   echo $dlocal
    # Puree VisIt pas capable de proposer de fixer VISIT_PLUGIN_DIR...
-   sed "s?$HOME/.visit?$dlocal?" CMakeLists.txt > p
+   sed "s?$HOME/.visit?$dlocal?" CMakeLists.txt
+   # Switch to c++14
+   sed -i 's/PROJECT(lata_database)/PROJECT(lata_database)\n set(CMAKE_CXX_STANDARD 14)/' CMakeLists.txt
+
    #sed "s?$HOME/.visit/2.?$dlocal/2.?;s?$HOME/.visit?$dlocal/current?" CMakeLists.txt > p
    #tkdiff  CMakeLists.txt p
-   mv p CMakeLists.txt
-  # rm -f CMakeCache*
    if [ "$TRUST_CC_BASE_EXTP" != "" ]
    then
       export OMPI_CXX=$TRUST_CC_BASE_EXTP
       export OMPI_CC=$TRUST_cc_BASE_EXTP
       export MPICH_CXX=$OMPI_CXX
       export MPICH_CC=$OMPI_CC
-   fi  
-   cmake . -DCMAKE_CXX_COMPILER=$TRUST_CC  -DCMAKE_C_COMPILER=$TRUST_cc -DCMAKE_CXX_STANDARD=11
-   [ ! -f Makefile ] && echo "Echec du construction du Makefile par xml2makefile dans ${Build}_plugin" && exit -1
+   fi
+   cmake . -DCMAKE_CXX_COMPILER=$TRUST_CC  -DCMAKE_C_COMPILER=$TRUST_cc -DCMAKE_CXX_STANDARD=14
+   [ ! -f Makefile ] && echo "Echec du construction du Makefile par CMake dans ${Build}_plugin" && exit -1
 
    cd ..
-    
+
 fi
 cd ${Build}
 
 #######################
 # Compilation du plugin
 # ######################
-$TRUST_MAKE || exit -1
-echo
-   # Inutile d'essayer rajouter dans le package les librairies car visit-install les efface a l'installation
+$TRUST_MAKE
 
-echo "$plugin plugin is up to date under VisIt."
+echo "-> Done: $plugin plugin is up to date under VisIt!"
 cd ../../../
 rm -rf plugins
