[scripts] 'baltik_validation' can use a validation test list

diff --git a/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche b/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
--- a/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
+++ b/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
@@ -82,6 +82,21 @@ get_list_prm()
     done
 }
 
+get_list_validation_from_a_file()
+{
+  # Check the existence of the file containing the customized list of validation test cases
+  [[ ! -f ${1} ]] && exit 1
+  
+  for t in $(cat ${1})
+  do
+    # The test is added unless the line is commented with a '#'
+    if [[ $(echo ${t} | grep -Ev "^ *#") ]]
+    then
+      echo ${project_directory}/${t}
+    fi
+  done
+}
+
 genere_fiche()
 {
     GENERE_COURBE=$TRUST_ROOT/Validation/Outils/Genere_courbe/
@@ -196,7 +211,20 @@ pdf_only=0
 with_sjob=0
 [ "$1" = "-parallel_sjob" ] && with_sjob=1 && shift
 
-liste_prm=`get_list_prm`
+if [[ "${testListValidation}" == "" ]]
+then
+  # Standard case : all validation tests are launched
+  liste_prm=`get_list_prm`
+else
+  # A customized list of validation tests has been given
+  liste_prm=$(get_list_validation_from_a_file "${testListValidation}")
+  if [[ $? -ne 0 ]]
+  then
+    echo -e "Error : a problem occured when reading the file"
+    exit 1
+  fi
+fi
+
 [ "$1" = "-from-Times" ] && shift && file=$1 && shift&& liste_prm=`get_list_prm_from_Times $file` 
 force=0
 [ "$*" != "" ] && echo On passe les cas precises && liste_prm="$@" && force=1 
diff --git a/bin/baltik/share/baltik/bin/baltik_validation b/bin/baltik/share/baltik/bin/baltik_validation
--- a/bin/baltik/share/baltik/bin/baltik_validation
+++ b/bin/baltik/share/baltik/bin/baltik_validation
@@ -48,8 +48,27 @@ if [ "${TRUST_ROOT}" = "" ]
 then
     TRUST_environnement_error
 fi
+
 reduit=0
 [ "$1" = "reduit" ] && reduit=1 && shift
+
+if [[ "$1" != "" ]]
+then
+  testListValidation="$(pwd)/${1}"
+  echo -e "A test list of validation is used : ${testListValidation}"
+  
+  # Check the existence of the file containing the customized list of validation test cases
+  if [[ ! -f ${testListValidation} ]]
+  then
+    echo -e "Error: the file '${testListValidation}' doesn't exist !"
+    exit 1
+  fi
+  
+  export testListValidation
+  shift
+fi
+
+[ "$1" = "" ] && [ $# -eq 1 ] && shift
 
 # verification du nombre d'arguments
 if [ $# -ne 0 ]
