Adaptation of validation scripts for Jenkins run: + Lance_gen_fiche should fail when archiving fails. + Less verbose validation.

diff --git a/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche b/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
--- a/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
+++ b/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
@@ -17,7 +17,9 @@ get_list_prm_from_Times()
   for cas in `awk '{print $NF}' $file`
     do
     cadt=`find $Rapports_auto_root/Validation/Rapports_automatiques -name $cas -follow | grep -v '/src/'`
-    list=$list" "$cadt
+    if [ ! -f $cadt/skip_prm ]; then
+      list=$list" "$cadt
+    fi
     done
   
   # Complete with other PRM (to get new ones) at top of the list
@@ -71,49 +73,49 @@ genere_fiche()
     fi 
     if [ $concurent -eq 0 ] ||  [ ! -d BUILD/$cas/build ]
     then
-    [ ! -d BUILD ] && echo `pwd` pas de build && exit 
-        echo $cas non existant on lance la generation de la fiche $dir
-        #  pwd
-    # GF le / apres dir est important pour ne pas copier le lien
-    # le -L pour copier les liens en tant que fichier 
-    cp -rL $dir/ BUILD
-    chmod -R +w  BUILD/$cas
-    cd BUILD/$cas
-    touch Running$OPTIONS_PRM
-    ${GENERE_COURBE}/Run $prm $opt  $OPTIONS_PRM 1> run$OPTIONS_PRM.log 2>&1
+      [ ! -d BUILD ] && echo `pwd` pas de build && exit 
+      echo $cas non existant on lance la generation de la fiche $dir
+      # GF le / apres dir est important pour ne pas copier le lien
+      # le -L pour copier les liens en tant que fichier 
+      cp -rL $dir/ BUILD
+      chmod -R +w  BUILD/$cas
+      cd BUILD/$cas
+      touch Running$OPTIONS_PRM
+      echo "@@@ About to execute Run script ..."
+      ${GENERE_COURBE}/Run $prm $opt  $OPTIONS_PRM 1> run$OPTIONS_PRM.log 2>&1
+      status=$?
+      echo "@@@ Done executing Run script."
 
-    if [ ! -f build/rapport.pdf ]
-        then
-        echo pb avec le rapport $dir
-        ko=1
-    else
-        
-        cp build/rapport.pdf $org/archives/$cas.pdf
-     ###   ${GENERE_COURBE}/src/genere $prm 
-        if [ $pdf_only -eq  0 ]
-         then
-        ${GENERE_COURBE}/Run $prm $opt -archive 1>arc.log 2>&1
-        status=$?
-        if [ $status -ne 0 ] 
-        then
-        echo "pb avec Run_archive $dir"
-        ko=2
-        else
-        mv preserve.tgz $org/archives/$cas.tgz
-        rm -rf build
-        fi
-        fi
-    fi
-    if [ $ko -eq 0 ]
-    then
-        mv     Running$OPTIONS_PRM ../deps_$(basename $dir)
-    else
-        mv     Running$OPTIONS_PRM KO$OPTIONS_PRM
-    fi
+      if [ ! -f build/rapport.pdf ] || [ "$status" != "0" ]
+          then
+          echo "!!! Error with report $dir"
+          ko=1
+      else
+          cp build/rapport.pdf $org/archives/$cas.pdf
 
-    cd $org
+          if [ $pdf_only -eq  0 ]; then
+            echo "@@@ About to execute Run -archive ..."
+            ${GENERE_COURBE}/Run $prm $opt -archive 1>arc.log 2>&1
+            status=$?
+            echo "@@@ Done Run -archive"
+            if [ $status -ne 0 ]; then
+              echo "!!!! Error with Run_archive $dir"
+              ko=2
+            else
+              mv preserve.tgz $org/archives/$cas.tgz
+              rm -rf build
+            fi
+          fi
+      fi
+      if [ $ko -eq 0 ]; then
+         mv     Running$OPTIONS_PRM ../deps_$(basename $dir)
+      else
+         mv     Running$OPTIONS_PRM KO$OPTIONS_PRM
+      fi
+
+      cd $org
     else
-    echo BUILD/$dir existe and mode concurrent, on ne lance pas la fiche
+      echo BUILD/$dir existe and mode concurrent, on ne lance pas la fiche
     fi
 
     return $ko
@@ -139,7 +141,7 @@ with_sjob=0
 liste_prm=`get_list_prm`
 [ "$1" = "-from-Times" ] && shift && file=$1 && shift&& liste_prm=`get_list_prm_from_Times $file` 
 force=0
-[ "$*" != "" ] && echo on passe les cas precises && liste_prm="$@" && force=1 
+[ "$*" != "" ] && echo On passe les cas precises && liste_prm="$@" && force=1 
 echo $liste_prm
 echo " cas en double ? "
 for dir in $liste_prm
@@ -155,7 +157,9 @@ then
   do 
     cas=`basename $dir`
     
+    echo "@@ About to genere_fiche"
     genere_fiche $dir
+    echo "@@ Done genere_fiche"
   
     [ $ko -ne 0 ] && echo pb au run ??? && exit -1
   done
