[Jupyter] Validation form can now be written as Jupyter notebook.
+ Run_fiche launches a browser with the notebook
+ automatic NR cases extraction working
+ archive_resultat partially working
+ example validation form updated and serves as reference documentation

diff --git a/Validation/Outils/Genere_courbe/Run b/Validation/Outils/Genere_courbe/Run
--- a/Validation/Outils/Genere_courbe/Run
+++ b/Validation/Outils/Genere_courbe/Run
@@ -9,7 +9,7 @@
 usage()
 {
   echo "Usage:"
-  echo "  `dirname $0`/Run ./src/fichier.prm [ -help ] [  -dest dir dir ] [ -not_run ] | [ -post_run ] | [ -suite_run ] [ -test_run ] [ -get_list_cas_nr ] [ -parallel_run ] [ -parallel_sjob ] [ -nb_pas_dt_max N ] [ -archive ] $*"
+  echo "  `dirname $0`/Run ./src/fichier.prm [ -help ] [  -dest dir dir ] [ -not_run ] | [ -post_run ] | [ -suite_run ] [ -test_run ] [ -get_list_cas_nr ] [ -parallel_run ] [ -parallel_sjob ] [ -nb_pas_dt_max N ] [ -archive ] [ -prepare_only ] $*"
   echo "  the other options are passed to genererCourbes.py"
   exit 0
 }
@@ -42,10 +42,31 @@ fi
 [ "$1" = "-help" ] && usage
 shift
 
-[ "$1" = "-help" ] && usage
+# Est ce une fiche Jupyter?
+is_jupyter=false
+if [[ "$prm" == *.ipynb ]]; then
+  is_jupyter=true
+fi
+
+# If a directory is provided as main argument, try to find the PRM or Jupyter notebook associated to it.
+if [ "$prm" != "-help" ] && [ -d $prm ]; then
+  if ls $prm/src/*.prm 1>/dev/null 2>&1; then 
+    prm=`ls $prm/src/*.prm`
+  else 
+    if ls $prm/*.ipynb 1>/dev/null 2>&1; then
+      prm=`ls $prm/*.ipynb`
+      is_jupyter=true
+    else
+      echo "Neither a PRM nor a Jupyter notebook??"
+      exit -1
+    fi
+  fi
+fi
+
 run=1
 parallel=0
 orig="."
+prepare_only=0
 if [ "$1" = "-dest" ]
 then
     orig=`pwd`
@@ -65,7 +86,14 @@ fi
 [ "$1" = "-parallel_run" ] && parallel=1 && shift
 [ "$1" = "-parallel_sjob" ] && parallel=2 && shift
 [ "$1" = "-nb_pas_dt_max" ] && shift && NBPASMAX=$1 && shift
-prm=`basename $prm .prm`.prm
+[ "$1" = "-prepare_only" ] && run=0 && shift && prepare_only=1
+
+if $is_jupyter ; then
+  prm=`basename $prm .ipynb`.ipynb
+else 
+  prm=`basename $prm .prm`.prm
+fi
+
 if [ "$1" = "-archive" ] 
 then
   bash $DIR/archive_resultat $prm
@@ -76,9 +104,9 @@ then
     echo "-> Error! Directory src does not exist."
     exit
 fi
-if [ ! -f "$orig/src/$prm" ]
+if [ ! -f "$orig/src/$prm" ] || $is_jupyter && [ ! -f "$orig/$prm" ]
 then
-    echo "-> Error! Report template file $prm does not exist."
+    echo "-> Error! Report template file $orig/(src/)$prm does not exist."
     exit
 fi
 # Prevent parallel_run 
@@ -92,7 +120,6 @@ then
   echo Sserver detected. Will use Salloc.
 fi
 
-
 # Copy content of src directory to build directory go to ./build directory and
 # execute "./prepare" script (if exists).
 # WARNING: prepare_gen is executed even if -not_run is given
@@ -100,6 +127,13 @@ fi
 if [ $run -ne -2 ]
     then
     $DIR/prepare_gen $orig || exit -1
+    if $is_jupyter; then
+       # Execute Python cells of the Jupyter notebook up to the runCases() invocation - this is now part of the 'prepare' process
+       if ! python $DIR/get_nr_cases_jup.py "$orig/$prm" 1>/dev/null 2>&1; then
+         echo "Failed runing begining of Jupyter Notebook."
+         exit -1 
+       fi
+    fi
     if [ "$NBPASMAX" != "" ] 
     then
     echo "We modify .data to run only on $NBPASMAX time step"
@@ -113,7 +147,7 @@ if [ $run -ne -2 ]
     done
     fi
     # dans le cas ou on copie le cas test on verifie que le prm est identique dans src et dans build (cas des prm generes par prepare)
-    if [ $run -eq -1 ]
+    if [ $run -eq -1 ] && ! $is_jupyter
     then
     modif=`diff $orig/src/*prm build/${prm}`
     if [ "$modif" != "" ]
@@ -126,12 +160,27 @@ if [ $run -ne -2 ]
     fi
     fi
 else
-# $DIR/prepare_gen $orig
     mkdir -p build
     cd build
     ln -sf $orig/src/* .
     cd ..
 fi
+
+if [ $prepare_only -eq 1 ]; then
+   exit 0
+fi
+
+## From this point onwards, Jupyter is not supported by this script - 
+## (the begining of the script is kept since it is responsible for runnning the prepare script
+## and ameding the .data files ...)
+if $is_jupyter ; then
+   echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+   echo "Jupyter notebooks should not be executed with the 'Run' script!"
+   echo "Use Run_fiche instead."
+   echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+   exit -1
+fi
+
 # If "run" requested, run trust testcases and PreRequis command found in the
 # header of the .prm file
 
@@ -140,7 +189,7 @@ if [ $run -eq 1 ]
 then
   python $DIR/src/genererCourbes.py --get_cmd_to_run=yes  -p $prm $*   > cmds
   python $DIR/scripts/get_nb_procs.py $prm  > nb_procs || exit -1
-
+    
   get_version
   echo "================================================"
   echo "-> Running commands in the ./build/cmds file ..."
@@ -199,7 +248,14 @@ then
 
         fi
      done
+     
+     ##
+     ##  NOW wait FOR ALL BACKGROUND PROCESSES TO TERMINATE
+     ##
      wait
+     ##
+     ##
+     ##
 
      # Lancement du post_run 
      bash ./post_run.sh
diff --git a/Validation/Outils/Genere_courbe/archive_resultat b/Validation/Outils/Genere_courbe/archive_resultat
--- a/Validation/Outils/Genere_courbe/archive_resultat
+++ b/Validation/Outils/Genere_courbe/archive_resultat
@@ -7,7 +7,7 @@
 # which relies itself on src/fileList.py
 #
 
-echo "usage $0 src/file.prm [archive_name]"
+echo "usage $0 {src/file.prm|file.ipynb} [archive_name]"
 
 # cd to the real directory in case of link
 cd `pwd -P`
@@ -15,15 +15,42 @@ prm=$1
 log_file=archive.log
 
 #
+# Check valid input
+# 
+if [ ! -f $prm ]; then
+   echo "File $prm does not exist!"
+   exit -1
+fi
+is_jupyter=false
+if [[ "$prm" == *.ipynb ]]; then
+  is_jupyter=true
+else 
+   if [[ ! "$prm" == *.prm ]]; then
+      echo "Invalid parameter to archive_resultat: $prm"
+      exit 
+   fi
+fi
+base_prm=$(basename $prm)
+
+DIR=`dirname $0`
+DIR=`(cd $DIR; pwd)`
+
+#
 # Prepare preserve dir and check computation has run:
 #
 rm -rf preserve archive.log
 mkdir preserve
-DIR=`dirname $0`
-DIR=`(cd $DIR; pwd)`
-$DIR/Run $prm -not_run  -o test.pdf 1>$log_file 2>&1
-[ ! -f build/test.pdf ] && echo "Unable to generate report. Exiting. Launch 'Run_fiche' before 'Run_fiche -archive'." && exit 1
-rm -rf build/test.pdf
+if ! $is_jupyter; then
+    $DIR/Run $prm -not_run  -o test.pdf 1>$log_file 2>&1
+    [ ! -f build/test.pdf ] && echo "Unable to generate report. Exiting. Launch 'Run_fiche' before 'Run_fiche -archive'." && exit 1
+    rm -rf build/test.pdf
+else  # For Jupyter, make it simpler, by default just check the build directory is there
+    echo "Jupyter archiving -- warning: it is **your** responsibility to have an up-to-date 'build' directory ..."
+    if [ ! -d build ]; then 
+       echo "'build' directory not found!!"
+       exit -1
+    fi
+fi
 
 ##
 ## Main
@@ -31,7 +58,7 @@ rm -rf build/test.pdf
 echo "ARCHIVE: Copying necessary files ..."
 cp build/version_utilisee build/temps_total build/used_files preserve
 cp -r src/* preserve
-cp build/$1 preserve   # In F5 for example, the PRM itself is generated from a Python script ...
+cp build/$base_prm preserve   # In F5 for example, the PRM itself is generated from a Python script ...
 cp -r build/.tmp preserve  # Mandatory for "make validation"
 chmod -R +w preserve
 cd build 
@@ -60,8 +87,16 @@ echo "ARCHIVE: Testing archive ..."
 tar zxf $archive.tgz
 cd preserve
 
-python $DIR/src/genererCourbes.py -p $prm --no_prereq -o ../old_rapport.pdf 1> ../$log_file 2>&1
-[ $? -ne 0 ] && echo "*** FAILED generating archive!! Last logs of (failed) report build can be seen in $log_file" &&  mv ../$archive.tgz ../${archive}_FAILED.tgz && exit 2
+if ! $is_jupyter; then
+    python $DIR/src/genererCourbes.py -p $base_prm --no_prereq -o ../old_rapport.pdf 1> ../$log_file 2>&1
+    status=$?
+else  # Jupyter notebook
+    curr_dir=`pwd`
+    env JUPYTER_RUN_OPTIONS="-not_run -dest $curr_dir" jupyter nbconvert --to pdf --output "$curr_dir/../old_rapport.pdf" --execute ../$base_prm 1>../$log_file 2>&1
+    status=$?
+fi
+
+[ $status -ne 0 ] && echo "*** FAILED generating archive!! Last logs of (failed) report build can be seen in $log_file" &&  mv ../$archive.tgz ../${archive}_FAILED.tgz && exit 2
 cd ..
 gzip -f old_rapport.pdf
 rm -rf preserve 
diff --git a/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche b/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
--- a/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
+++ b/Validation/Outils/Genere_courbe/scripts/Lance_gen_fiche
@@ -39,16 +39,33 @@ get_list_prm_from_Times()
 
 get_list_prm()
 {
-    for dir in `find $Rapports_auto_root/Validation/Rapports_automatiques -name '*.prm' -follow  | grep '/src/'`
+    # PRM 
+    for f in `find $Rapports_auto_root/Validation/Rapports_automatiques -name '*.prm' -follow  | grep '/src/'`
       do
-      cas=`dirname $dir`
+      cas=`dirname $f`
       if [ "`basename $cas`" != "src" ]
       then
-      echo "$dir bizarre!!!!"
+        echo "$f is strange - a PRM not in a src folder!!!!"
+        return
       else
         dirn_cas=`dirname $cas`
         if [ ! -f $dirn_cas/skip_prm ] && [ ! -f $dirn_cas/src/skip_prm ]; then
           echo `dirname $cas`
+        fi
+      fi
+    done
+
+    # Jupyter notebooks
+    for f in `find $Rapports_auto_root/Validation/Rapports_automatiques -type f \( -name '*.ipynb' ! -path '*.ipynb_checkpoints*' \) -follow`
+      do
+      cas=`dirname $f`
+      if [ ! -d "$cas/src" ]
+      then
+        echo "$f is strange - missing src subfolder!!!!"
+        return
+      else
+        if [ ! -f $cas/skip_prm ] && [ ! -f $cas/src/skip_prm ]; then
+          echo $cas
         fi
       fi
     done
@@ -63,7 +80,16 @@ genere_fiche()
     cd $org
     mkdir -p BUILD archives
     dir=$1
+    is_jupyter=false
     prm=`ls $dir/src/*.prm`
+    if [ ! $? -eq 0 ]; then
+      prm=`ls $dir/*.ipynb`
+      if [ ! $? -eq 0 ]; then
+         echo ERROR: no PRM and no notebook file found!
+         exit 1
+      fi
+      is_jupyter=true
+    fi
     cas=`basename $dir`
     opt=""
     if [ $with_sjob -eq 1 ]
@@ -79,13 +105,22 @@ genere_fiche()
       cp -rL $dir/ BUILD
       chmod -R +w  BUILD/$cas
       cd BUILD/$cas
+      curr_dir=`pwd`
       # if the file KO has been created in a previous test, delete it for the current test
       rm -f KO*
       touch Running$OPTIONS_PRM
-      echo "@@@ About to execute Run script ..."
-      ${GENERE_COURBE}/Run $prm $opt  $OPTIONS_PRM 1> run$OPTIONS_PRM.log 2>&1
-      status=$?
-      echo "@@@ Done executing Run script."
+      if ! $is_jupyter; then   # PRM format 
+         echo "@@@ About to execute Run script (PRM) ..."
+         ${GENERE_COURBE}/Run $prm $opt  $OPTIONS_PRM 1> run$OPTIONS_PRM.log 2>&1
+         status=$?
+         echo "@@@ Done executing Run script."
+      else    # Jupyter format
+         echo "@@@ About to execute and export Jupyter notebook to PDF ..."
+         env JUPYTER_RUN_OPTIONS="$opt" jupyter nbconvert --to pdf --output "$curr_dir/build/rapport.pdf" --execute $prm 1>run$OPTIONS_PRM.log 2>&1
+         status=$?
+         echo "@@@ Done processing Jupyter notebook with exit status $status."
+      fi
+      
 
       if [ ! -f build/rapport.pdf ] || [ "$status" != "0" ]
           then
@@ -135,7 +170,7 @@ genere_fiche()
 }
 
 ###
-### MAIN
+### MAIN:q
 ###
 
 org=`pwd`
