Indentation ....

diff --git a/Validation/Outils/Genere_courbe/Run b/Validation/Outils/Genere_courbe/Run
--- a/Validation/Outils/Genere_courbe/Run
+++ b/Validation/Outils/Genere_courbe/Run
@@ -87,29 +87,29 @@ if [ $run -ne -2 ]
     then
     $DIR/prepare_gen $orig || exit -1
     if [ "$NBPASMAX" != "" ] 
-	then
-	echo "We modify .data to run only on $NBPASMAX time step"
-	for jdd in `find build -name '*'.data`
-	  do
+    then
+    echo "We modify .data to run only on $NBPASMAX time step"
+    for jdd in `find build -name '*'.data`
+      do
           mv $jdd $jdd.save
-	  # comme dans copie_cas_test sans le solveur 
-	    $TRUST_Awk -v NBPASMAX=$NBPASMAX '/tinit/ {print $0;print "\tnb_pas_dt_max", NBPASMAX ;getline}\
+      # comme dans copie_cas_test sans le solveur 
+        $TRUST_Awk -v NBPASMAX=$NBPASMAX '/tinit/ {print $0;print "\tnb_pas_dt_max", NBPASMAX ;getline}\
    !/nb_pas_dt_max/ {print $0}\
 ' $jdd.save > $jdd
-	done
+    done
     fi
     # dans le cas ou on copie le cas test on verifie que le prm est identique dans src et dans build (cas des prm generes par prepare)
     if [ $run -eq -1 ]
-	then
-	modif=`diff $orig/src/*prm build/${prm}`
-	if [ "$modif" != "" ]
-	then 
-	    echo "-> Problem with $orig/src/*prm and build/${prm}" >/dev/stderr
-	    echo "-> There is a difference between the prm file in build directory and the prm file in the src directory." >/dev/stderr
-	    diff $orig/src/*prm build/${prm} >/dev/stderr
-	    mv build build_err
-	    exit -1    
-	fi
+    then
+    modif=`diff $orig/src/*prm build/${prm}`
+    if [ "$modif" != "" ]
+    then 
+        echo "-> Problem with $orig/src/*prm and build/${prm}" >/dev/stderr
+        echo "-> There is a difference between the prm file in build directory and the prm file in the src directory." >/dev/stderr
+        diff $orig/src/*prm build/${prm} >/dev/stderr
+        mv build build_err
+        exit -1    
+    fi
     fi
 else
 # $DIR/prepare_gen $orig
@@ -156,24 +156,25 @@ then
             $SJOB_DIR/Salloc ./$cmd &
         else
 
-# See https://stackoverflow.com/questions/1537956/bash-limit-the-number-of-concurrent-jobs	
-function max_bg_procs {
-    if [[ $# -eq 0 ]] ; then
-       echo "Usage: max_bg_procs NUM_PROCS.  Will wait until the number of background (&)"
-       echo "           bash processes (as determined by 'jobs -pr') falls below NUM_PROCS"
-       return
-    fi
-    local max_number=$((0 + ${1:-0}))
-    while true; do
-       local current_number=$(jobs -pr | wc -l)
-       if [[ $current_number -lt $max_number ]]; then
-          break
-       fi
-       sleep 1
-    done
-}
-	    max_bg_procs $TRUST_NB_PROCS
-	    awk -F'"' '{print $2}' $cmd
+          # See https://stackoverflow.com/questions/1537956/bash-limit-the-number-of-concurrent-jobs    
+          function max_bg_procs {
+              if [[ $# -eq 0 ]] ; then
+                 echo "Usage: max_bg_procs NUM_PROCS.  Will wait until the number of background (&)"
+                 echo "           bash processes (as determined by 'jobs -pr') falls below NUM_PROCS"
+                 return
+              fi
+              local max_number=$((0 + ${1:-0}))
+              while true; do
+                 local current_number=$(jobs -pr | wc -l)
+                 if [[ $current_number -lt $max_number ]]; then
+                    break
+                 fi
+                 sleep 1
+              done
+          }
+
+        max_bg_procs $TRUST_NB_PROCS
+        awk -F'"' '{print $2}' $cmd
             bash ./$cmd &
         fi
      done
@@ -196,20 +197,20 @@ if [ $run -le -1 ]
 then
     list_tot=`python $DIR/src/genererCourbes.py -p $prm  --get_cmd_to_run=yes| grep get_total_time | sed "s/\.perf/.data/g" | sed "s/get_total_time//" | sed "s/\.\///g"  `
     if [ -f liste_cas_exclu_nr ]
-	then
-	list_cas_nr="" 
-	for cas in $list_tot
-	  do
-	  if [ "`grep $cas liste_cas_exclu_nr`" = "" ]
-	      then
-	      list_cas_nr=${list_cas_nr}" "$cas
-	  else
-	      echo not_in_nr    $cas not in nr
-	  fi
-	done
-	echo "liste_cas_nr" $list_cas_nr 
+    then
+    list_cas_nr="" 
+    for cas in $list_tot
+      do
+      if [ "`grep $cas liste_cas_exclu_nr`" = "" ]
+          then
+          list_cas_nr=${list_cas_nr}" "$cas
+      else
+          echo not_in_nr    $cas not in nr
+      fi
+    done
+    echo "liste_cas_nr" $list_cas_nr 
     else
-	echo "liste_cas_nr" $list_tot
+    echo "liste_cas_nr" $list_tot
     fi
     exit
 fi
@@ -217,14 +218,14 @@ if [ $run -ne 0 ]
 then
     if [ "`grep erreur_calcul temps_total`" != "" ]
     then 
-	echo
-	echo 
-	cat temps_total
-	echo
-	echo
-	echo "-> Error in: python $DIR/src/genererCourbes.py -p $prm $*"
-	echo "-> Search and fix all the previous errors."
-	exit 1
+    echo
+    echo 
+    cat temps_total
+    echo
+    echo
+    echo "-> Error in: python $DIR/src/genererCourbes.py -p $prm $*"
+    echo "-> Search and fix all the previous errors."
+    exit 1
     fi
 fi
 echo "=============================="
