171_RC4

diff --git a/bin/admin/connect_ftp b/bin/admin/connect_ftp
--- a/bin/admin/connect_ftp
+++ b/bin/admin/connect_ftp
@@ -11,9 +11,11 @@ export SECRET=incoming/y2k01/TRUST
 if [ ${#1} = 0 ] || [ $1 != "-no_ftp" ]
 then
 
-   ok=`cat << ! | ftp -iv | $TRUST_Awk 'BEGIN {ok=0} /Login successful/ {ok=1} END {print ok}'
+   ok=`(cat << ! | ftp -iv | $TRUST_Awk 'BEGIN {ok=0} /Login successful/ {ok=1} END {print ok}'
 open $TRUST_FTP
 !
+) & 
+$TRUST_ROOT/bin/KSH/wait_for $! 600 || (echo "Error: connect_ftp killed"; exit -1)
 `
 
    if [ $ok = 1 ]
@@ -23,6 +25,7 @@ open $TRUST_FTP
       echo "Connection to $TRUST_FTP unsuccessful !"
    #   exit
    fi
+   
    for DIR in $SECRET $PUBLIC
    do
       if [ "`existe_ftp $DIR`" = 1 ]
@@ -33,5 +36,6 @@ open $TRUST_FTP
 	 mkdir_ftp $DIR
       fi
    done
+   
 fi
 
diff --git a/bin/admin/cp_ftp b/bin/admin/cp_ftp
--- a/bin/admin/cp_ftp
+++ b/bin/admin/cp_ftp
@@ -9,27 +9,26 @@ do
    plus=$i
 done
 rep=$plus
-mkdir_ftp $SECRET 1>/dev/null
+mkdir_ftp $rep 1>/dev/null
+
 for file in $files
 do
    # Ajout du del car parfois impossible de copier
    # il met une erreur en disant fichier not found !
-   echo "Copy of the $file file on ftp://$TRUST_FTP/$rep directory"
-   mkdir_ftp $rep 1>/dev/null
+   echo "Copy of the $dir/$file file on ftp://$TRUST_FTP/$rep directory"
    p="" && [ "`ftp -help 2>&1 | grep '\-p'`" != "" ] && p=p # Passive mode utile sur les machines virtuelles
-
-   cat << ! | ftp -iv$p | grep 'Opening BINARY'
+(
+   cat << ! | ftp -iv$p | grep 'Transfer complete'
 open $TRUST_FTP
 lcd $dir
-cd ../..
-epsv
-cd $rep
+cd "/"$rep
 bin
 del $file
 put $file
 !
+) &
+$TRUST_ROOT/bin/KSH/wait_for $! 600 || (echo "Error: cp_ftp killed"; exit -1)
 
+   [ $? != 0 ] && echo "Error to send data"
 done
-#On enleve:
-#chmod 644 $file
 
diff --git a/bin/admin/mkdir_ftp b/bin/admin/mkdir_ftp
--- a/bin/admin/mkdir_ftp
+++ b/bin/admin/mkdir_ftp
@@ -3,22 +3,24 @@
 # Argument $1 nom du repertoire
 nom=${1%.}
 nom=${nom%/}
+echo "Make the $1 directory on ftp://$TRUST_FTP"
+
 if [ "`existe_ftp $nom`" != 1 ]
 then
    dir=`dirname $nom`
    rep=`basename $nom`
-   echo "  $nom on $TRUST_FTP is created"
    p="" && [ "`ftp -help 2>&1 | grep '\-p'`" != "" ] && p=p # Passive mode utile sur les machines virtuelles
-
-   cat << ! | ftp -iv$p | $TRUST_Awk '/MKD command/ || /File exists/ {print $0}'
+(
+   cat << ! | ftp -iv$p | grep 'created'
 open $TRUST_FTP
-cd ../..
-cd $dir
+cd "/"$dir
 mkdir $rep
 chmod 755 $rep
 !
+) &
+$TRUST_ROOT/bin/KSH/wait_for $! 600 || (echo "Error: mkdir_ftp killed"; exit -1)
 
+   [ $? != 0 ] && echo "Error: $nom on $TRUST_FTP is NOT created"
 else
-   echo "  $nom on $TRUST_FTP already exists"
+   echo "$nom on $TRUST_FTP already exists"
 fi
-
diff --git a/bin/admin/mv_ftp b/bin/admin/mv_ftp
--- a/bin/admin/mv_ftp
+++ b/bin/admin/mv_ftp
@@ -1,8 +1,12 @@
 #!/bin/bash
-
-cat << ! | ftp -iv | grep 'Opening BINARY'
+# Renomme le fichier passe en argument
+echo "Rename the $1 file to $2 file on ftp://$TRUST_FTP/ directory"
+(
+cat << ! | ftp -iv | grep 'Rename'
 open $TRUST_FTP
-cd ../..
-rename $1 $2
+rename "/"$1 "/"$2
 !
+) &
+$TRUST_ROOT/bin/KSH/wait_for $! 600 || (echo "Error: mv_ftp killed"; exit -1)
 
+[ $? != 0 ] && echo "Error command failed"
diff --git a/bin/admin/rm_ftp b/bin/admin/rm_ftp
--- a/bin/admin/rm_ftp
+++ b/bin/admin/rm_ftp
@@ -1,22 +1,11 @@
 #!/bin/bash
-# Liste le repertoire passe en argument
-
-cat << ! | ftp -iv 2>&1 | grep rw
+# Supprime le fichier passe en argument
+echo "Delete of the $1 file on ftp://$TRUST_FTP/ directory"
+(
+cat << ! | ftp -iv 2>&1 | grep 'Delete'
 open $TRUST_FTP
-cd ../..
-delete $1
+delete "/"$1
 !
-
-# En cas d'echec, essai en mode anonymous
-if [ $? != 0 ]
-then
-
-   cat << ! | ftp -n 2>&1 | grep rw
-open $TRUST_FTP
-user anonymous triou@cea.fr
-cd ../..
-delete $1
-!
-
-fi
+) &
+$TRUST_ROOT/bin/KSH/wait_for $! 600 || (echo "Error: rm_ftp killed"; exit -1)
 
diff --git a/bin/admin/rmdir_ftp b/bin/admin/rmdir_ftp
--- a/bin/admin/rmdir_ftp
+++ b/bin/admin/rmdir_ftp
@@ -13,6 +13,7 @@ find_directory()
    done
 }
 
+echo "Remove the $1 directory on ftp://$TRUST_FTP"
 dir=`dirname $1`
 rep=`basename $1`
 
@@ -21,17 +22,17 @@ rep=`basename $1`
 repertoires=`find_directory $1`" "$1
 for repertoire in $repertoires
 do
-   echo "Efface $repertoire sur $TRUST_FTP"
-
-   cat << ! | ftp -iv 2>&1 | $TRUST_Awk '/MKD command/ || /File exists/ || /failed/ {print $0}'
+(
+   cat << ! | ftp -iv 2>&1 | grep 'Remove'
 open $TRUST_FTP
-cd ../..
-cd $repertoire
+cd "/"$repertoire
 mdelete *
 mdelete .*
 cd ..
 rmdir `basename $repertoire`
 !
+) &
+$TRUST_ROOT/bin/KSH/wait_for $! 600 || (echo "Error: rmdir_ftp killed"; exit -1)
 
 done
 
diff --git a/bin/baltik/share/baltik/bin/baltik_configure b/bin/baltik/share/baltik/bin/baltik_configure
--- a/bin/baltik/share/baltik/bin/baltik_configure
+++ b/bin/baltik/share/baltik/bin/baltik_configure
@@ -78,6 +78,15 @@ fi
 echo "Done."
 echo ""
 
+preconfigure=$project_directory/share/bin/pre_configure
+if [ -f $preconfigure ]
+then
+    echo "Executing $preconfigure"
+    $preconfigure
+    [ $? -ne 0 ] && echo "Error" && exit -1
+    echo "Done"
+    echo ""
+fi
 
 echo "Checking dependencies ..."
 
@@ -102,22 +111,13 @@ echo "Done."
 echo ""
 
 
-preconfigure=$project_directory/share/bin/pre_configure
-if [ -f $preconfigure ]
-then
-    echo "Executing $preconfigure"
-    $preconfigure
-    [ $? -ne 0 ] && echo "Error" && exit -1
-    echo "Done"
-    echo ""
-fi
 
 
 echo "Preparing sources ..."
 
 # initialisation du repertoire de construction
 project_build_directory="${project_directory}/build/src"
-rm -f $project_build_directory/* 
+rm -f $project_build_directory/*  $project_build_directory/exec*/CMakeCache.txt 
 
 rm -f $project_build_directory/*/CMakeCache.txt
 mkdir -p $project_build_directory
@@ -127,8 +127,14 @@ while read name path
 do
   echo "Adding source files from project $name"
   sourcedir="$path/src"
+ 
   for suf in h cpp f c hxx cxx
     do
+    test_uniq=`find  $sourcedir -follow -name "*."${suf} -exec basename {} \; | sort | uniq -d`
+    if [ "${test_uniq}" != "" ]
+	then
+	conflicting_files_error ${test_uniq}  `find  $sourcedir -follow -name ${test_uniq}`
+	fi
     for sourcefile in `find  $sourcedir -follow -name "*."${suf}`
       do
 	# filename=${sourcefile##*/}
@@ -142,22 +148,42 @@ do
 	      # on regarde si le source file  est dans un repertoire merged
 		dirsource=`dirname ${sourcefile}`
 		dirsource=`basename $dirsource`
+		
+		dirlink=`dirname ${file_link}`
+		dirlink=`basename $dirlink`
 
-		if [ "$dirsource" = "merged" ]
+		[ "$dirsource" = "patch" ] && [ "$dirlink" = "patch" ]&& conflicting_files_error ${filename} ${file_link} ${sourcefile}
+		
+		
+		# Pour anciennes viersions
+		if [ "$dirsource" = "merged" ] ||  [ "$dirsource" = "patch" ]
 		    then
 		    # echo "linkfile" ${linkfile} ${file_link}
 		    # echo "source " ${sourcefile}
-		    echo "file merged ?"
+		    echo "patch file  ?"
 		    if [ ${sourcefile} -nt ${file_link} ]
 			then
 			echo "ok we replace ${file_link} with ${sourcefile}"
 			rm -f ${linkfile}
 			ln -s ${sourcefile} ${linkfile}
 		    else
-			echo "File in merged directory ${sourcefile} not newer that" ${file_link}
+			echo "File in directory ${sourcefile} not newer that" ${file_link}
 			conflicting_files_error ${filename} ${file_link} ${sourcefile}
 		    fi
-		else
+		elif  [ "$dirlink" = "patch" ]
+		    then
+		    # echo "linkfile" ${linkfile} ${file_link}
+		    # echo "source " ${sourcefile}
+		    echo "patch file  ?"
+		    if [ ${file_link} -nt ${sourcefile} ]
+			then
+			echo "ok we keep ${file_link} instead of ${sourcefile}"
+		
+		    else
+			echo "File in directory ${sourcefile} not newer that" ${file_link}
+			conflicting_files_error ${filename} ${file_link} ${sourcefile}
+		    fi
+		  else
 	      # xterm
 		    conflicting_files_error ${filename} ${file_link} ${sourcefile}
 		fi
@@ -253,6 +279,8 @@ do
 	    exit 1
     fi
     libraires_flag=`extract_field "$prerequis_description" librairies_flag`
+    configure_flag=`extract_field "$prerequis_description" configure_flag`
+    export configure_flag
     includes_add="$includes_add -I${project_directory}/local/${prerequis_name}/include"
     librairies_add="$librairies_add -L${project_directory}/local/${prerequis_name}/lib/ $libraires_flag"
     export includes_add
@@ -482,7 +510,7 @@ printf "\t@env TRUST_ROOT_ORG=$TRUST_ROOT $BALTIK_ROOT/bin/baltik_install `dirna
 printf "\n"                                                     >> $project_makefile
 printf "# help terminal \t: open a xterm with TRUST_TESTS... \n" >> $project_makefile
 printf "terminal :\n" >> $project_makefile
-printf "\t source $TRUST_ROOT/env/Init_TRUST; env TRUST_TESTS=\`pwd\`/build/tests/all/  Rapports_auto_root=\`pwd\`/build/tests/share/all/ project_directory=\`pwd\` exec_optim=${exec_optim} exec=${exec_optim} exec_debug=$exec_debug xterm\n" >> $project_makefile
+printf "\t source $TRUST_ROOT/env/env_TRUST.sh; env TRUST_TESTS=\`pwd\`/build/tests/all/  Rapports_auto_root=\`pwd\`/build/tests/share/all/ project_directory=\`pwd\` exec_optim=${exec_optim} exec=${exec_optim} exec_debug=$exec_debug xterm\n" >> $project_makefile
 
 phony=""
 for type in $list_cible
@@ -536,6 +564,20 @@ do
 done
 
 
+env_file=$project_directory/env_${project_name}.sh
+echo "Creation $env_file"
+
+echo " . $TRUST_ROOT/env/env_TRUST.sh
+export project_directory=${project_directory}
+export PATH=\${project_directory}/build/xdata:\$PATH
+export TRUST_TESTS=\${project_directory}/build/tests/all/
+export Rapports_auto_root=\${project_directory}/build/tests/share/all/ 
+export exec_opt=\${project_directory}/${project_executable_name}_opt
+export exec=\${project_directory}/${project_executable_name}_opt
+export exec_semi_opt=\${project_directory}/${project_executable_name}_semi_opt
+export exec_pg=\${project_directory}/${project_executable_name}_opt_pg
+export exec_gcov=\${project_directory}/${project_executable_name}_opt_gcov
+export exec_debug=\${project_directory}/${project_executable_name}" > $env_file
 echo "Done."
 echo ""
 
diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -36,7 +36,9 @@ make_tools()
    echo "==========================="
    echo "$MESSAGE tools and plugins:"
    echo "==========================="
-   reps="Outils/lance_test_seq_par Outils/cppcheck Outils/triou2doxygen Outils/lata2dx Outils/Slotting Outils/TRIOXDATA Outils/doxygen  doc/Coverage doc"
+   reps="Outils/lance_test_seq_par Outils/cppcheck Outils/triou2doxygen Outils/lata2dx Outils/Slotting Outils/TRIOXDATA Outils/doxygen"
+   [ "$TRUST_DISABLE_MEDCOUPLING" = 0 ] && [ "$TRUST_DISABLE_MED" = 0 ] && [ "$TRUST_DISABLE_MPI" = 0 ] && reps=$reps" Outils/ICoCo"
+   reps=$reps" doc/Coverage doc"
    [ "$TRUST_DISABLE_VALGRIND" != 1 ] && reps=$reps" Outils/valgrind"
    [ "$TRUST_DISABLE_GNUPLOT" != 1 ] && reps=$reps" Outils/gnuplot"
    [ "$TRUST_DISABLE_MED" = 0 ] && [ "$TRUST_DISABLE_GMSH" != 1 ] && reps=$reps" Outils/Gmsh"
@@ -61,7 +63,15 @@ make_tools()
          fi
       fi
    done
-   [ "$err_tool" = 1 ] && echo "A tool failed to build. Contact TRUST support." && exit -1
+   if [ "$err_tool" = 1 ]
+   then
+      echo "A tool failed to build. Contact TRUST support." && echo "BUILD_TOOLS=KO" | tee -a $COMPILE && exit -1
+   else
+      echo "END"
+      echo >>$COMPILE
+      echo "BUILD_TOOLS=OK" | tee -a $COMPILE
+      echo >>$COMPILE
+   fi
 }
 
 make_jade_batch()
@@ -73,7 +83,7 @@ make_jade_batch()
 #PBS -l select=8:ncpus=8:mpiprocs=1
 #PBS -l walltime=02:00:00
 cd $TRUST_ROOT
-#source env/Init_TRUST
+#source env/env_TRUST.sh
 cd \$PBS_O_WORKDIR
 export HOST=jade
 export TRUST_MAKE=\"make -j8\"
@@ -95,7 +105,7 @@ make 1>make.log 2>&1" > sub_file
 ###################
 # DEBUT DU SCRIPT #
 ###################
-[ "$TRUST_ROOT" = "" ] && echo "Error. TRUST_ROOT is empty. Initialize TRUST environment." && exit -1 
+[ "$TRUST_ROOT" = "" ] && echo "Error. TRUST_ROOT is empty. Initialize TRUST environment." && echo "BUILD_EXEC=KO" && exit -1 
 
 # Options
 depend=0
@@ -117,7 +127,8 @@ CLEAN="" && MESSAGE="Building" && [ "${1%clean}" != "$1" ] && CLEAN=clean && MES
 [ ! -d $TRUST_ROOT/lib ] && mkdir $TRUST_ROOT/lib
  
 COMPILE=$TRUST_ROOT/compile_TRUST$COMM$OPT"_"$TRUST_ARCH"_"$HOST_BUILD".log"
-echo>$COMPILE
+echo "TRUST compilation on $HOST the `date` ...">$COMPILE
+echo>>$COMPILE
 
 # Nettoyage/Reconstruction des outils uniquement
 if [ "$1" = tools ]
@@ -153,9 +164,8 @@ then
 fi
 \cd $TRUST_ROOT
 
-[ ${#TRUST_F77} = 0 ] && echo "No fortran compiler defined in $TRUST_F77 variable." && exit -1
-[ ${#TRUST_CC} = 0 ] && echo "No C++ compiler defined in $TRUST_CC variable." && exit -1
-
+[ ${#TRUST_F77} = 0 ] && echo "No fortran compiler defined in $TRUST_F77 variable." && echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
+[ ${#TRUST_CC} = 0 ] && echo "No C++ compiler defined in $TRUST_CC variable." && echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
 echo "$MESSAGE of version : $TRUST_ROOT"
 echo "For arch : $TRUST_ARCH_CC"
 echo "\$OPT=$OPT"
@@ -210,8 +220,8 @@ then
 	       echo $ECHO_OPTS "-> $exec is deleted."
 	       rm -f $exec
 	    fi 
-	    echo "Contact TRUST support."
-	    exit -1
+	    echo "A library failed to build. Contact TRUST support."
+	    echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
 	 fi
          \cd ..
       fi
@@ -256,7 +266,7 @@ then
          if [ $LIB = ${LIB#lib} ]
          then
             echo "Library name in makefile of $dir is not correct."
-            exit -1
+	    echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
          fi
       fi
    #
@@ -268,7 +278,7 @@ then
    #
       if [ "$CLEAN" = "" ]
       then
-         $TRUST_ROOT/bin/KSH/check_sources.sh || exit -1 
+         $TRUST_ROOT/bin/KSH/check_sources.sh || (echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1)
       fi     
    #
    # Compilation selon les machines
@@ -349,7 +359,7 @@ then
 	    echo $ECHO_OPTS "-> $exec is deleted."
 	    rm -f $exec
 	 fi 
-	 exit -1
+	 echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
       fi
       #
       # Verifie le bon etat des .o crees (.o vides ou autre)
@@ -359,7 +369,7 @@ then
          i=${file%.cpp};i=${i%.f};i=${i%.c};o=$i.o
          [ -f $o ] && [ ! -s $o ] && echo "$dir/$file badly compiled then the .o file is deleted..." && rm -f $o && err=1
       done
-      [ $err = 1 ] && exit -1
+      [ $err = 1 ] && echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
       \cd $TRUST_ROOT
    done
 elif [ "$CLEAN" == "" ]
@@ -371,7 +381,7 @@ then
    mklibs=`ls $TRUST_ROOT/bin/mklibs* 2>/dev/null` && $mklibs 
    [ ${#MonoDir} = 0 ] && MonoDir=$TRUST_ROOT/MonoDir$COMM$OPT
    echo "Build with COMM=\"$COMM\" and OPT=\"$OPT\" under the directory $MonoDir"
-   [ ${#TRUST_ROOT} = 0 ] && echo "TRUST_ROOT variable is not defined !" && exit
+   [ ${#TRUST_ROOT} = 0 ] && echo "TRUST_ROOT variable is not defined !" && echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit
 
    # Creation de ce qui n'existe peut etre pas :
    [ ! -d $TRUST_ROOT/exec ] && mkdir $TRUST_ROOT/exec
@@ -458,7 +468,7 @@ then
 	 then
             echo $dir 
 	    # Verifie les sources
-	    $TRUST_ROOT/bin/KSH/check_sources.sh || exit -1
+	    $TRUST_ROOT/bin/KSH/check_sources.sh || (echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1)
             # Met a jour le fichier instancie (mk_Instancie a reporter dans check.sh? au lieu de make depend ?)
             mk_Instancie
             # Recherche des fichiers de $dir
@@ -561,15 +571,15 @@ then
          MonoDir=${MonoDir_base}$opt
 	 [ "$opt" = "_debug" ] && MonoDir=${MonoDir_base}
 	 mkdir -p $MonoDir/src
-	 \cd $MonoDir/src || exit -1
+	 \cd $MonoDir/src || (echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1)
          case $opt in
           _opt) build_type="Release" ;;
           _debug) build_type="Debug" ;;
-          _opt_pg) build_type="Profil" ;;
-          _opt_gcov)  build_type=Coverage ;;
+          _prof) build_type="Profil" ;;
+          _gcov)  build_type="Coverage" ;;
           _semi_opt) build_type="semi_opt";;
           _opt_avx)  build_type="Release_avx";;
-	  *) echo $opt not for cmake in $0;  exit -1 ;;
+	  *) echo $opt not for cmake in $0; echo "BUILD_EXEC=KO" | tee -a $COMPILE; exit -1 ;;
          esac;
 
          CHOIX_MAKE multiple
@@ -577,7 +587,9 @@ then
 
          cmake $TRUST_ROOT/src -DCMAKE_INSTALL_PREFIX=$TRUST_ROOT -DCMAKE_BUILD_TYPE=$build_type -Ukernel $MODE_SPECIAL -DCOMPIL_DYN=${COMPIL_DYN}
 
-         [ $? != 0 ] && echo 'Problem of configuring ' && exit -1
+         [ $? != 0 ] && echo 'Problem of configuring.' && echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
+	 # GF pour eviter message 
+	 export MAKELEVEL=0
 
          $MAKE 
          status=$?
@@ -585,12 +597,16 @@ then
          then
 	    echo 'Problem of compiling ->' 
 	    $MAKE 
-	    exit -1
+	    echo "BUILD_EXEC=KO" | tee -a $COMPILE && exit -1
 	    break
          fi
       done
    fi
    echo "END"
+   echo >>$COMPILE
+   echo "cibles="$cibles | tee -a $COMPILE
+   echo "BUILD_EXEC=OK" | tee -a $COMPILE
+   echo >>$COMPILE
 fi
 #
 # Pour HP et realiser un executable share lib portable (SHLIB_PATH) :
@@ -609,7 +625,16 @@ if [ "$CLEAN" != "" ]
 then
    \cd $TRUST_ROOT
    # GF il ne faut pas effacer exec ici, sinon le configure risque de planter
-   rm -rf lib/  include/ MonoDir*
+   #rm -rf lib/ include/ MonoDir*
+   # il ne faut pas effacer lib/src/LIBMPI ici, sinon l'installation Installer_TRUST plante, idem pour include/backward
+   #rm -rf `ls lib/src/* | grep -v LIBMPI` include/ MonoDir* # equivaut a rm -rf LIB* et non a rm -rf lib/src/LIB* donc faire une boucle
+   rm -rf MonoDir*
+   rm -f include/*.h
+   rm -f lib/*.a
+   for rep_lib in `ls lib/src | grep -v LIBMPI` 
+   do
+      rm -rf lib/src/$rep_lib
+   done
    # Atelier
    if [ -d $rep_dev ]
    then
diff --git a/bin/lance_test b/bin/lance_test
--- a/bin/lance_test
+++ b/bin/lance_test
@@ -55,18 +55,31 @@ analyse_fichier_colonne()
    # Ne compare pour le moment que les fichiers paralleles avec ceux sequentiels
    if [ $type = "par" ]
    then
-      rm -f compare_sonde.log
       let egal=0
-      list_output=`ls $NOM2"_"*.son $NOM2"_"*.out 2>/dev/null` 
+      list_output=`ls  $NOM2"_"*.out 2>/dev/null` 
       total=`echo $list_output | wc -w | $TRUST_Awk '{print $1}'`
+      seuil=1e-3
+      if [ -f seuil_controle_bilan ]
+	  then
+	  seuil=`cat seuil_controle_bilan`
+	  echo "Control of out with $seuil"
+      fi
+
       for par_output in $list_output
       do
          seq_output=${par_output#PAR_}
-	 compare_sonde $seq_output $par_output 1>>compare_sonde.log 2>&1
-	 [ $? = 0 ] && let egal=$egal+1
+	 compare_sonde $seq_output $par_output -max_delta -seuil_erreur $seuil 1>compare_${seq_output}.log 2>ompare_${seq_output}.err
+	 if [ $? = 0 ] 
+           then
+          let egal=$egal+1 
+	else
+         echo error with files ${seq_output}
+	 cat compare_${seq_output}.log
+	fi
       done
       PLOT=$egal/$total
       ecarts_plots=1 && [ $egal = $total ] && ecarts_plots=0
+      [ $ecarts_plots = 1 ] && echo error with files out 
       case ${#PLOT} in
 	3) PLOT="...."$PLOT;;
 	4) PLOT="..."$PLOT;;
@@ -150,12 +163,20 @@ liste()
    add_test_case_from_validation || exit -1
    echo " "
    echo "Searching test cases in $ref. Please wait..."
-   testslist=`find $ref/ -follow -name *.lml.gz -print 2>/dev/null | sed 's#'"$ref/"'##'`
+   testslist=`find $ref/ -follow -name *.lml.gz -print 2>/dev/null | sed 's#'"$ref/"'##' | sort`
    # Pour eviter les problemes des .lml.gz sortis de gestion de conf
    if [ "`element_gere_en_configuration.sh .`" = git ]
    then
       #liste=`\cd $ref;git-ls-files */*/*.lml.gz` 
-      liste=`\cd $ref;git-ls-files $testslist`
+      liste=`\cd $ref;git-ls-files $testslist | sort`
+      nbold=`echo $liste | wc -w`
+      nbnew=`echo $testslist | wc -w`
+      nbdif=`echo "$nbnew-$nbold" | bc -l`
+      if [ $nbdif != 0 ]
+      then
+         echo "Warning: $nbdif test case(s) not in configuration management => Commit your test case(s) on git!"
+	 exit -1
+      fi
    else
       #liste=`\cd $ref;ls */*/[A-N]*.lml.gz 2>/dev/null;ls */*/[O-Z]*.lml.gz 2>/dev/null;ls */*/[a-n]*.lml.gz 2>/dev/null;ls */*/[o-z]*.lml.gz 2>/dev/null;ls */*/__*.lml.gz 2>/dev/null;ls */*/[0-9]*.lml.gz 2>/dev/null`
       liste=$testslist
@@ -332,7 +353,7 @@ add_test_case_from_validation()
       #############################################################################
       # Creation eventuelle de nouveaux cas tests depuis les fiches de validation #
       #############################################################################
-      for FICHE_ROOT in `cd ${Rapports_auto_root} 2>/dev/null && find Validation/Rapports_automatiques -name '*'.prm | $TRUST_Awk -F/src '!/build/ {print $1}'`
+      for FICHE_ROOT in `cd ${Rapports_auto_root} 2>/dev/null && find  Validation/Rapports_automatiques -follow -name '*'.prm | $TRUST_Awk -F/src '!/build/ {print $1}'`
       do
          ####################
 	 # Nouveau cas test #
@@ -383,6 +404,7 @@ add_test_case_from_validation()
 		  then
 		     if [ ! -f $TRUST_TESTS/$DIRECTORY/$test/lien_fiche_validation ]
 		     then
+                        org=`pwd`
 			if [ ! -d $TRUST_TESTS/$DIRECTORY/$test ]
 			then
 		           cd $TRUST_TESTS/$DIRECTORY
@@ -395,11 +417,11 @@ add_test_case_from_validation()
 			if [ "$TRUST_SCM" = 1 ] 
 			then
 			   CHECKOUT . 1>/dev/null 2>&1
-			   MKELEM lien_fiche_validation 1>mkelem.log 2>&1
-			   [ $? != 0 ] && echo "Error during the creation of `pwd`/lien_fiche_validation" && cat mkelem.log && exit -1	     
+			   MKELEM lien_fiche_validation 
+			   [ $? != 0 ] && echo "Error during the creation of `pwd`/lien_fiche_validation" &&  exit -1	     
 			fi
 			echo "Creation of $test/lien_fiche_validation"  
-			cd - 1>/dev/null 2>&1
+			cd $org 1>/dev/null 2>&1
 		     fi
 		  else
 		      # le fichier lien est il a jour
@@ -446,9 +468,10 @@ add_test_case_from_validation()
 			   then
 			      cd $TRUST_TESTS/$DIRECTORY/$test
 			      CHECKOUT . 1>/dev/null 2>&1
-			      MKELEM $test.lml.gz 1>mkelem.log 2>&1
-			      [ $? != 0 ] && echo "Error when creating the file `pwd`/$test.lml.gz" && cat mkelem.log && exit -1	 
+			      MKELEM $test.lml.gz 
+			      [ $? != 0 ] && echo "Error when creating the file `pwd`/$test.lml.gz" && exit -1	 
 			   fi
+			      cd $TRUST_TESTS
 			   rm -r -f $REP_TMP
 			fi
 		     fi	 
@@ -465,7 +488,7 @@ add_test_case_from_validation()
 # Debut du script #
 ###################
 
-[ ${#TRUST_ROOT} = 0 ] && echo "TRUST environment not initialized. Go to the bin directory of TRUST installation and run: . ./Init_TRUST" && exit
+[ ${#TRUST_ROOT} = 0 ] && echo "TRUST environment not initialized. Go to the env directory of TRUST installation and run: source ./env_TRUST.sh" && exit
 
 LANG=C
 PETSC_DEBUG=0 && [ $PETSC_DEBUG = 1 ] && echo "ATTENTION PETSC_DEBUG MIS A 1 !!!" 
@@ -476,7 +499,6 @@ echo "Usage: `basename $0` [-print] [-distant] [-nomail] [-efface] [-no_timeout]
 # Les fichiers .tests_$exec et .tests_$exec.html seront dans ce repertoire
 # et les cas de references en dessous linkes avec les fichiers
 # des repertoires contenus dans tests/Reference
-#[ -z "$DIPHA_ROOT" ] && . Init_TRUST 1>/dev/null 2>&1
 AWK=$TRUST_ROOT/bin/AWK
 GMON_DIR=$TRUST_TMP/gmon && rm -r -f $GMON_DIR
 GMON_DIR="" # On desactive la construction d'un profile complet (assez long)
@@ -486,7 +508,7 @@ then
     Rapports_auto_root=$TRUST_ROOT
 else
     echo "Use of $Rapports_auto_root directory for validation instead of \$TRUST_ROOT"
-    if [ "$ref" = "$TRUST_ROOT/tests" ]
+    if [ "$ref" = "$TRUST_ROOT/tests" ] && [ "$Rapports_auto_root" != "$TRUST_ROOT" ]
     then
        echo "You must change TRUST_TESTS variable and define Rapports_auto_root"
        exit -1
@@ -629,7 +651,7 @@ then
     if [ $choix != 0 ]
     then
        #liste=`ls */$choix/$choix.lml.gz 2>/dev/null`
-       liste=`find ./ -follow -name $choix.lml.gz -print 2>/dev/null | sed 's#'"./"'##'`
+       liste=`find ./ -follow -name $choix.lml.gz -print 2>/dev/null | sed 's#'"./"'##' | sort`
        if [ ${#liste} != 0 ]
        then
 	  choix="M"
@@ -644,8 +666,8 @@ then
 	        cas=`basename $cas`
 		#lmlgz=`ls */$cas/$cas.lml.gz 2>/dev/null`
 		#if [ -f ${lmlgz%lml.gz}data ] || [ "`ls */$cas/lien_fiche_validation 2>/dev/null`" != "" ]
-                lmlgz=`find ./ -follow -name $cas.lml.gz -print 2>/dev/null | sed 's#'"./"'##'`
-		if [ -f ${lmlgz%lml.gz}data ] || [ "`find ./ -follow -name lien_fiche_validation -print 2>/dev/null | sed 's#'"./"'##'`" != "" ]
+                lmlgz=`find ./ -follow -name $cas.lml.gz -print 2>/dev/null | sed 's#'"./"'##' | sort`
+		if [ -f ${lmlgz%lml.gz}data ] || [ "`find ./ -follow -name lien_fiche_validation -print 2>/dev/null | sed 's#'"./"'##' | sort`" != "" ]
 		then
 		   liste=$liste" "$lmlgz
 		fi
@@ -661,9 +683,20 @@ then
     # Verifier si liste non vide
     [ "$liste" = "" ] && echo "Error: No test cases found." && exit -1
     # Verifier si liste contient cas en double
-    fulllist=`echo $liste | xargs dirname | xargs basename -a`
-    uniqlist=`echo $liste | xargs dirname | xargs basename -a | sort -u`
-    [ ${#fulllist} != ${#uniqlist} ] && echo "Error: Test cases duplicate => Check that 2 test cases don't have the same name!" && exit -1
+    # l option -a n est pas disponible sur toutes les machines donc passage a une boucle for
+    #fulllist=`echo $liste | xargs dirname | xargs basename -a`
+    #uniqlist=`echo $liste | xargs dirname | xargs basename -a | sort -u`
+    fulllist=""
+    for i in `echo $liste`
+    do
+       j=`dirname $i`
+       fulllist=$fulllist" "`basename $j`
+    done
+    uniqlist=`echo $fulllist | sort -u`
+    nbold=`echo $fulllist | wc -w`
+    nbnew=`echo $uniqlist | wc -w`
+    nbdif=`echo "$nbnew-$nbold" | bc -l`
+    [ $nbdif != 0 ] && echo "Error: Test cases duplicate => Check that $nbdif test cases don't have the same name!" && exit -1
     k=0
     succes=0
     succes_par=0
@@ -740,7 +773,7 @@ then
          export GCOV_PREFIX
           [ $choix = 0 ] && rm -rf ${GCOV_PREFIX}
        fi    
-  # find $TRUST_ROOT/MonoDir$COMM"_opt_gcov"/src/. -name '*'.gcda | xargs rm -f
+  # find $TRUST_ROOT/MonoDir$COMM"_gcov"/src/. -name '*'.gcda | xargs rm -f
     fi
     coverage_gprof=0 && [ ${exec%_pg}   != $exec ] && [ $choix = 0 ] && coverage_gprof=1
     
@@ -786,6 +819,15 @@ then
 	      i=""
            fi
 	fi
+	# Discard MED test case if no MED capabilities
+	if [ "$TRUST_DISABLE_GMSH" = 1 ]
+	then
+	   if [ "`grep "gmsh " $REP/* 2>/dev/null`" != "" ]
+	   then
+              echo "Test $i skipped (no gmsh)"
+	      i=""
+           fi
+	fi
 	# Discard PARALLEL ONLY test case if no MPI capabilities
 	if [ "$TRUST_DISABLE_MPI" = 1 ]
 	then
@@ -796,8 +838,15 @@ then
 	   [ "`grep -i hypre $REP/* 2>/dev/null`" != "" ]		&& i=""
 	   [ "`grep -i boomeramg $REP/* 2>/dev/null`" != "" ]		&& i=""
 	   [ "`grep -i Check_solver.sh $REP/* 2>/dev/null`" != "" ]	&& i=""
+	   [ "`grep -i 'Testeur_MEDCoupling' $REP/* 2>/dev/null`" != "" ] && i=""
            [ "$i" = "" ] &&  echo "Test $iisa skipped (no MPI)"
 
+	fi
+        if [ -f $REP/skipped ]
+	then
+	echo "Test $i skipped (file skipped)"
+
+	i=""
 	fi
 	[ $choix != "0" ] && [ ${choix#P_} = $choix ] && [ $choix != $k ] && [ $choix != "M" ] && i=""
 	if [ ${#i} != 0 ]
@@ -1109,6 +1158,7 @@ then
 			    SPU="....."
 		            # Nouveau: compare les fichiers colonnes
 			    analyse_fichier_colonne
+				[ $ecarts_plots -ne 0 ] && PB=254
 			    if [ $PB -eq '0' ]
 			    then
 				if [ "$type" = "seq" ]
@@ -1229,8 +1279,8 @@ echo $ECHO_OPTS "Successful tests cases :"$succes"/"$tests"\n" >> $SORTIE
 # GF le test est faux car PAR est modififie par chaque cas
 if [ $tests_par  -ne 0  ]
 then
-   echo $ECHO_OPTS "Successful tests cases in parallel mode :"$succes_par"/"$tests_par"\n" >> $SORTIE
-   (echo $ECHO_OPTS "Successful tests cases in parallel mode :"$succes_par"/"$tests_par"\n" >> $fichier) 2>/dev/null
+   echo $ECHO_OPTS "Successful tests cases in parallel mode :"$succes_par"/"$tests_par"" >> $SORTIE
+   (echo $ECHO_OPTS "Successful tests cases in parallel mode :"$succes_par"/"$tests_par"" >> $fichier) 2>/dev/null
 fi
 
 # Sort le temps CPU de la suite de tests
@@ -1239,6 +1289,7 @@ $TRUST_Awk -F'|' '/s\|/ {gsub("s","",$4);CPU+=$4;i++} END {if (i!=0) print i" te
 
 if [ ${#choix} = 0 ] || [ $choix = 0 ]
 then
+   echo >> $SORTIE
    echo "Parallel tests cases :" | tee -a $SORTIE
    for file in $liste
    do
@@ -1250,6 +1301,7 @@ then
    done | sort | uniq -c | tee -a $SORTIE
 fi
 
+echo >> $SORTIE
 if [ $succes = $tests ]
 then
    echo $ECHO_OPTS "Successful result." >> $SORTIE
@@ -1293,7 +1345,11 @@ then
          [ "$dest" != "" ] && cat $message | grep -v ' ecarts |' | mail_ -s \"[lance_test] Unsuccesful no-regression tests on $HOST \(without warning\)\" $dest 
       fi
    fi
+   # Liste des cas tests ayant pose probleme
+   echo $ECHO_OPTS "List of unsuccessful tests cases :\n`cat $rep_tests/liste`\n" >> $SORTIE
+   (echo $ECHO_OPTS "List of unsuccessful tests cases :\n`cat $rep_tests/liste`\n" >> $fichier) 2>/dev/null
 fi
+echo >> $SORTIE
 rm -f $message
 
 #[ $checkin = 0 ] && CHECKIN $SORTIE
