Add git_ssh mode on CCRT machines

diff --git a/bin/admin/envoie_TRUST_arch b/bin/admin/envoie_TRUST_arch
--- a/bin/admin/envoie_TRUST_arch
+++ b/bin/admin/envoie_TRUST_arch
@@ -163,8 +163,13 @@ do
       ################
       # Mode git_ssh #
       ################ 
+      elif [ "`liste_machines git_ssh | grep $adr`" != "" ] && [[ $adr != *".ccc.cea.fr" ]]
+      then
+          echo "KO $adr machine => git_ssh mode not supported with TRUST for non CCRT machines!"
+          liste_machines_KO=$liste_machines_KO" "$adr
       elif [ "`liste_machines git_ssh | grep $adr`" != "" ]
       then
+
 	 echo "Sources updated by Git on $log@$adr:$WORKDIR/$version at "`date '+%H:%M:%S'` 
 	 # Si premiere installation:
 	 #if [ "`ssh_ -o ConnectTimeout=10 -o BatchMode=yes $log@$adr -n ls $WORKDIR/$version/TRUST/.git 1>/dev/null 2>&1;echo $?`" != 0 ]
@@ -175,8 +180,89 @@ do
 	 #echo "Launching the update by ssh on $log@$adr at "`date '+%H:%M:%S'`   
 	 
 	 # no updated with TRUST
-         echo "KO $adr machine => git_ssh mode no supported with TRUST for the moment!" 
-         liste_machines_KO=$liste_machines_KO" "$adr
+
+	    # Creation eventuelle du repertoire:
+	 ssh_command '[ ! -d '$WORKDIR/$version' ] && mkdir -p '$WORKDIR/$version
+         echo "Update git repo (TRUST and externalpackages) on irene-ccrt with triou/TMA"
+         echo "git push origin_irene-ccrt Livraison:triou/TMA"
+         (cd $TRUST_ROOT ; git push origin_irene-ccrt Livraison:triou/TMA )
+         (cd $TRUST_ROOT/externalpackages ; git push origin_irene-ccrt Livraison:triou/TMA )
+	 echo "
+cd $WORKDIR
+mkdir -p $version
+cd $version
+pwd
+[ ! -d TRUST ] && git clone /ccc/work/cont002/den/triou/trust-code.git TRUST
+cd TRUST
+[ ! -d externalpackages ] && git clone /ccc/work/cont002/den/triou/trust-code.git/externalpackages.git externalpackages
+git checkout triou/TMA
+git checkout .
+git pull
+cd externalpackages
+git checkout triou/TMA
+git checkout .
+git pull" > $TRUST_TMP/ssh_com
+         ssh -o "StrictHostKeyChecking no" -o ConnectTimeout=30 -o BatchMode=yes $log@$adr 'bash -s '$WORKDIR/$version < $TRUST_TMP/ssh_com || echo "No access"
+
+	 rsync_log=$Build/rsync_$machine.log
+         if [ "`rsync -e 'ssh -o StrictHostKeyChecking=no' --dirs --delete --dry-run $TRUST_ROOT/RELEASE_NOTES $log@$adr:/tmp 1>/dev/null 2>&1;echo $?`" = 0 ]
+         then
+	    if [ "$a_jour_TRUST_tar_files" != 1 ]
+	    then
+	       echo " "
+	       echo "Searching for files to rsync..."
+	       a_jour_TRUST_tar_files=1
+	       mise_a_jour_TRUST_tar -files_only -without_version
+	       # Creation du fichier pattern pour --include-from
+	       cd $TRUST_ROOT
+	       rm -f $Build/rsync_include_from
+	       for file in $Build/TRUST.files
+	       do
+	          VOB=${file%.files}
+		  echo $VOB >> $Build/rsync_include_from
+		  cat $file >> $Build/rsync_include_from
+	       done
+	       echo "$Build/rsync_include_from updated."
+	       echo " "
+	    fi
+
+	    echo "rsync of sources on $log@$adr:$WORKDIR/$version at "`date '+%H:%M:%S'`
+	    cd $TRUST_ROOT/.. #sinon rsync plante...
+            for VOB in $VOBS
+	    do
+	       # -delete ne marche pas avec --files-from. A savoir. Voir: http://stackoverflow.com/questions/1813907/rsync-delete-files-from-list-dest-does-not-delete-unwanted-files
+	       rsync -e 'ssh -o StrictHostKeyChecking=no' --stats -aiHD --delete --files-from=$Build/$VOB.files --timeout=1000 . $log@$adr:$WORKDIR/$version
+	    done | grep -v "^\." 1>>$rsync_log 2>&1 # On filtre pour n'avoir que les fichiers modifies/deleted remotely
+	    if [ $? != 0 ]
+	    then
+               echo "KO $adr machine: rsync error. See $rsync_log"
+               liste_machines_KO=$liste_machines_KO" "$adr
+	    fi
+	    cd $TRUST_ROOT
+
+	    # Lancement par ssh:
+	    option=""
+	    #if [ "${machine:0:10}" = irene-ccrt ] || [ "${machine:0:6}" = cobalt ]
+	    if [ "${machine:0:6}" = cobalt ]
+	    then
+	       # CR bugges sur CCRT, on debugge:
+	       option="sh -xv "
+               option=""
+	       # machine=$machine".bak" # Pourquoi CR_$machine est abime?
+	       # On ne lance plus sur la frontale
+	       #ssh_command "export WORKBASE=$WORKBASE;rm -f myjob_$machine.*.o  myjob_$machine.*.e;cd $WORKDIR/$version/TRUST/bin/admin;ccc_msub sub_maj_$machine" &
+	       #echo "Launching in background the update by ssh then ccc_msub on $log@$adr at "`date '+%H:%M:%S'`
+               # je teste sur la frontale !!
+	       ssh_command "export WORKBASE=$WORKBASE;cd $WORKDIR/$version/TRUST/bin/admin;$option./mise_a_jour_TRUST_arch -rsync 1>~/CR_$machine 2>&1" &
+	       echo "Launching in background the update by ssh on $log@$adr at "`date '+%H:%M:%S'`
+	    else
+	       # On lance sur la frontale
+	       ssh_command "export WORKBASE=$WORKBASE;cd $WORKDIR/$version/TRUST/bin/admin;$option./mise_a_jour_TRUST_arch -rsync 1>~/CR_$machine 2>&1" &
+	       echo "Launching in background the update by ssh on $log@$adr at "`date '+%H:%M:%S'`
+	    fi
+         fi
+
+
 	 
       ##################
       # Mode rsync_ssh #
