Test adastra

diff --git a/bin/admin/envoie_TRUST_arch b/bin/admin/envoie_TRUST_arch
--- a/bin/admin/envoie_TRUST_arch
+++ b/bin/admin/envoie_TRUST_arch
@@ -8,19 +8,27 @@ ssh_command()
     # Le sh devant mise_a_jour_TRUST_arch est important sur titane!!
     # Comprends pas pourquoi...
     # Creation d'un fichier de commandes car probleme si le SHELL n'est pas bash 1> 2> pas reconnu
+    BATCHMODE=" -o BatchMode=yes "
+    SSHP=""
+    if [ "`liste_machines ssh_pass | grep $adr`" != "" ]
+    then
+       SSHPASS=`awk -v adr=$adr '($2==adr) {print $6}' ~/.netrc | head -1`
+       SSHP="sshpass -p $SSHPASS "
+       BATCHMODE=""
+    fi
     command=`mktemp_`
     echo > $command
     # Sur certaines machines un Killed by signal 1 empeche l'execution (supermuc par exemple)
     [ $adr != supermuc.lrz.de ] && echo ". ~/.bashrc 1>/dev/null 2>&1" >> $command
     echo $* >> $command
-    if [ "`ssh_ -o ConnectTimeout=30 -o BatchMode=yes $log@$adr -n pwd 1>/dev/null 2>&1;echo $?`" = 0 ]
+    if [ "`$SSHP ssh_ -o ConnectTimeout=30 $BATCHMODE $log@$adr -n pwd 1>/dev/null 2>&1;echo $?`" = 0 ]
     then
-       scp -o "StrictHostKeyChecking no" -o ConnectTimeout=10 -o BatchMode=yes $command $log@$adr:~/command_$machine 1>/dev/null 2>&1
+       $SSHP scp -o "StrictHostKeyChecking no" -o ConnectTimeout=10 $BATCHMODE $command $log@$adr:~/command_$machine 1>/dev/null 2>&1
        # Add -X to have DISPLAY ? not on jean-zay cause it hangs
        opt_="-X" && [ "${machine:0:8}" = jean-zay ] && opt_=""
        [ "${adr#mezel}" != "$adr" ] && opt_=""
        [ "${adr#topaze}" != "$adr" ] && opt_=""
-       ssh $opt_ -o "StrictHostKeyChecking no" -o ConnectTimeout=10 -o BatchMode=yes $log@$adr -n 'chmod +x ~/command_'$machine';~/command_'$machine 2>/dev/null
+       $SSHP ssh $opt_ -o "StrictHostKeyChecking no" -o ConnectTimeout=10 $BATCHMODE $log@$adr -n 'chmod +x ~/command_'$machine';~/command_'$machine 2>/dev/null
     fi
     rm -f $command
 }
@@ -134,7 +142,15 @@ do
    #machine=`echo $adr | awk -F"." '{print $1}'`
    machine=`echo $adr | awk -F"." '{print $1}' | awk -F"-gw" '{print $1}'` # 09/2015 Modification des acces SSH au TGCC *-gw.ccc.cea.fr
    version=$WORKBASE$machine
-   log=`awk -v adr=$adr '($2==adr) {print $4}' ~/.netrc | head -1`      
+   log=`awk -v adr=$adr '($2==adr) {print $4}' ~/.netrc | head -1`
+   BATCHMODE=" -o BatchMode=yes "
+   SSHP=""
+   if [ "`liste_machines ssh_pass | grep $adr`" != "" ]
+   then
+      SSHPASS=`awk -v adr=$adr '($2==adr) {print $6}' ~/.netrc | head -1`
+      SSHP="sshpass -p $SSHPASS "
+      BATCHMODE=""
+   fi
    ssh_log=$Build/ssh_$machine.log
    echo "ssh on $machine the `date` ...">$ssh_log
    if [ "$log" = "" ]
@@ -142,7 +158,7 @@ do
       echo "KO $adr machine not reported in ~/.netrc"
       liste_machines_KO=$liste_machines_KO" "$adr
    # Les machines git_cron ne sont pas accessibles par ssh
-   elif [ "`liste_machines git_cron | grep $adr`" = "" ] && [ "`ssh_ -o ConnectTimeout=30 -o BatchMode=yes $log@$adr -n pwd 1>>$ssh_log 2>&1;echo $?`" != 0 ]
+   elif [ "`liste_machines git_cron | grep $adr`" = "" ] && [ "`$SSHP ssh_ -o ConnectTimeout=30 $BATCHMODE $log@$adr -n pwd 1>>$ssh_log 2>&1;echo $?`" != 0 ]
    then
       echo "KO $adr machine not accessible via ssh. See $ssh_log" 
       liste_machines_KO=$liste_machines_KO" "$adr
@@ -161,8 +177,9 @@ do
       ##########################################################################
       # 4 modes supportes:
       # git_cron  : git des sources depuis la machine et build lance par crontab  => no updated with TRUST
-      # git_ssh   : git des sources depuis la machine et build lance par ssh      => no updated with TRUST
+      # git_ssh   : git des sources depuis la machine et build lance par ssh      => no updated with TRUST, was used for TGCC on a bare repo
       # rsync_ssh : rsync des sources vers la machine et build lance par ssh
+      # ssh_pass  : rsync des sources vers la machine et build lance par sshpass
       # sftp_ssh  : sftp des sources vers la machine et build lance par ssh 
       # sinon     : scp des sources vers la machine et build lance par ssh 
       ##########################################################################
@@ -385,6 +402,87 @@ git pull" > $TRUST_TMP/ssh_com
 	 else
             rsync -e 'ssh -o StrictHostKeyChecking=no' --dirs --delete --dry-run $TRUST_ROOT/RELEASE_NOTES $log@$adr:/tmp 1>>$rsyn_log 2>&1
             echo "KO $adr machine => rsync_ssh mode error. See $rsync_log" 
+            liste_machines_KO=$liste_machines_KO" "$adr
+	 fi
+
+
+
+      ##################
+      # Mode ssh_pass #
+      ##################
+      # On teste si rsync marche sinon on bascule sur le mode scp+ssh
+      elif [ "`liste_machines ssh_pass | grep $adr`" != "" ]
+      then
+	 rsync_log=$Build/rsync_$machine.log
+	 echo "rsync_sshpass on $machine the `date` ...">$rsync_log
+	 SSHPASS=`awk -v adr=$adr '($2==adr) {print $6}' ~/.netrc | head -1`
+	 log=`awk -v adr=$adr '($2==adr) {print $4}' ~/.netrc | head -1`
+         if [ "`sshpass -p $SSHPASS rsync -e 'ssh -o StrictHostKeyChecking=no' --dirs --delete --dry-run $TRUST_ROOT/RELEASE_NOTES $log@$adr:/tmp 1>/dev/null 2>&1;echo $?`" = 0 ]
+         then
+	    if [ "$a_jour_TRUST_tar_files" != 1 ]
+	    then
+	       echo " "
+	       echo "Searching for files to rsync..."
+	       a_jour_TRUST_tar_files=1
+	       mise_a_jour_TRUST_tar -files_only -without_version
+	       # Creation du fichier pattern pour --include-from
+	       cd $TRUST_ROOT
+	       rm -f $Build/rsync_include_from
+	       # Ajout des differents HOSTS non suivi par git
+	       (cd ../;find TRUST/env_src/ -name HOST_*.sh -type l) >> $Build/TRUST.files
+	       for file in $Build/TRUST.files
+	       do
+	          VOB=${file%.files}
+		  echo $VOB >> $Build/rsync_include_from
+		  cat $file >> $Build/rsync_include_from
+	       done
+	       echo "$Build/rsync_include_from updated."
+	       echo " "
+	    fi
+
+	    # Cas ou l'on efface la version
+	    if [ "$delete_version_machine_cible" = 1 ]
+	    then
+	       # On fait en 2 passes (car sinon conflit possible)
+	       echo "Deleting $WORKDIR/$version on $log@$adr..."
+	       sshpass -p $SSHPASS ssh -o "StrictHostKeyChecking no" -o ConnectTimeout=30 $log@$adr -n 'cd '$WORKDIR/$version';mv -f TRUST trashT;mkdir -p TRUST'
+	       sshpass -p $SSHPASS ssh -o "StrictHostKeyChecking no" -o ConnectTimeout=30 $log@$adr -n 'rm -r -f '$WORKDIR/$version'/trashT 1>/dev/null 2>&1' & 
+	       sshpass -p $SSHPASS ssh -o "StrictHostKeyChecking no" -o ConnectTimeout=30 $log@$adr -n 'cd '$WORKDIR/$version';mv -f Composants trashC;mkdir -p Composants'
+	       sshpass -p $SSHPASS ssh -o "StrictHostKeyChecking no" -o ConnectTimeout=30 $log@$adr -n 'rm -r -f '$WORKDIR/$version'/trashC 1>/dev/null 2>&1' & 
+            fi
+
+            # Creation eventuelle du repertoire avec les bonnes ACL :
+	    ssh_command '[ ! -d '$WORKDIR/$version' ] && [ -L ~/scripts_ACL ] && [ -e ~/scripts_ACL ] && sh ~/scripts_ACL/Create_version.sh '$WORKDIR/$version
+	    # Pour les autres machines, dossier inexistant
+	    ssh_command '[ ! -d '$WORKDIR/$version' ] && [ ! -L ~/scripts_ACL ] && mkdir -p '$WORKDIR/$version
+
+	    echo "rsync of sources on $log@$adr:$WORKDIR/$version at "`date '+%H:%M:%S'`
+	    cd $TRUST_ROOT/.. #sinon rsync plante...
+            for VOB in $VOBS
+	    do
+	       # -delete ne marche pas avec --files-from. A savoir. Voir: http://stackoverflow.com/questions/1813907/rsync-delete-files-from-list-dest-does-not-delete-unwanted-files
+	       sshpass -p $SSHPASS rsync -e 'ssh -o StrictHostKeyChecking=no' --stats -aiHD --delete --files-from=$Build/$VOB.files --timeout=1000 . $log@$adr:$WORKDIR/$version
+	    done | grep -v "^\." 1>>$rsync_log 2>&1 # On filtre pour n'avoir que les fichiers modifies/deleted remotely
+	    if [ $? != 0 ]
+	    then
+               echo "KO $adr machine: rsync error. See $rsync_log"
+               liste_machines_KO=$liste_machines_KO" "$adr
+	    fi
+	    cd $TRUST_ROOT
+
+	    # Creation eventuelle du lien:
+	    ssh_command '[ "$WORKDIR" != "" ] && [ "$WORKDIR" != "$HOME" ] && cd $HOME && rm -f '$version' && ln -sf $WORKDIR/'$version' .'
+
+	    # Lancement par ssh:
+	    option=""
+	    #if [ "${machine:0:10}" = irene-ccrt ] || [ "${machine:0:6}" = cobalt ]
+            # On lance sur la frontale
+            ssh_command "export WORKBASE=$WORKBASE;cd $WORKDIR/$version/TRUST/bin/admin;$option./mise_a_jour_TRUST_arch -rsync 1>~/CR_$machine 2>&1" &
+            echo "Launching in background the update by ssh on $log@$adr at "`date '+%H:%M:%S'`
+
+	 else
+            rsync -e 'ssh -o StrictHostKeyChecking=no' --dirs --delete --dry-run $TRUST_ROOT/RELEASE_NOTES $log@$adr:/tmp 1>>$rsyn_log 2>&1
+            echo "KO $adr machine => rsync_ssh mode error. See $rsync_log"
             liste_machines_KO=$liste_machines_KO" "$adr
 	 fi
 
